Document: dss
Title: Debian dss Manual
Author: <insert document author here>
Abstract: This manual describes what dss is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/dss/dss.sgml.gz

Format: postscript
Files: /usr/share/doc/dss/dss.ps.gz

Format: text
Files: /usr/share/doc/dss/dss.text.gz

Format: HTML
Index: /usr/share/doc/dss/html/index.html
Files: /usr/share/doc/dss/html/*.html
