find_library(SPIDERMONKEY_LIBRARY NAMES mozjs)
if(NOT SPIDERMONKEY_LIBRARY)
  find_library(SPIDERMONKEY_LIBRARY NAMES js)
endif()
if(NOT SPIDERMONKEY_LIBRARY)
  include(FindPkgConfig)
  pkg_search_module(SPIDERMONKEY REQUIRED libxul-unstable)
else()
  find_path(SPIDERMONKEY_INCLUDE_DIR js/jsapi.h)
  if(NOT SPIDERMONKEY_INCLUDE_DIR)
    find_path(SPIDERMONKEY_INCLUDE_DIR mozjs/jsapi.h)
    if(NOT SPIDERMONKEY_INCLUDE_DIR)
        find_path(SPIDERMONKEY_INCLUDE_DIR jsapi.h)
    endif()
  endif()

  include(FindPackageHandleStandardArgs)
  find_package_handle_standard_args(SpiderMonkey DEFAULT_MSG SPIDERMONKEY_LIBRARY SPIDERMONKEY_INCLUDE_DIR)

  if(SPIDERMONKEY_FOUND)
    set(SPIDERMONKEY_LIBRARIES ${SPIDERMONKEY_LIBRARY})
    set(SPIDERMONKEY_INCLUDE_DIRS ${SPIDERMONKEY_INCLUDE_DIR})
  endif()
endif()
