find_library(SPIDERMONKEY_LIBRARY NAMES mozjs)
find_path(SPIDERMONKEY_INCLUDE_DIR mozjs/jsapi.h)

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(SpiderMonkey DEFAULT_MSG SPIDERMONKEY_LIBRARY SPIDERMONKEY_INCLUDE_DIR)

if(SPIDERMONKEY_FOUND)
    set(SPIDERMONKEY_LIBRARIES ${SPIDERMONKEY_LIBRARY})
    set(SPIDERMONKEY_INCLUDE_DIRS ${SPIDERMONKEY_INCLUDE_DIR})
endif()
