#!/bin/sh
#
# Create a dss release tarball from git, including webroot customizations
#
# Johannes Winkelmann, johannes.winkelmann@aizo.com

# Ubuntu specific: add sprocketize to path
export PATH=$PATH:/var/lib/gems/1.8/bin/


GIT_REPO=git://gitorious.digitalstrom.org/dss/dss-mainline.git

if [ -z "$2" ]; then
	echo "Usage: $(basename $0) <release version string> <git branch name>"
	exit 1
fi

DSS_RELEASE_VERSION=$1
DSS_RELEASE_BRANCH=$2
TARGET_DIR=dss-$DSS_RELEASE_VERSION

if [ -d "$TARGET_DIR" ]; then
	echo "Target '$TARGET_DIR' exists; please remove first; exiting"
	exit 2
fi

git clone --depth 1 $GIT_REPO $TARGET_DIR
cd dss-$DSS_RELEASE_VERSION
git branch $DSS_RELEASE_BRANCH origin/$DSS_RELEASE_BRANCH
git checkout $DSS_RELEASE_BRANCH
git rev-parse HEAD > .dss_git_version
git branch|grep ^*|sed -e 's|^\*\s*||' > .dss_git_branch

git submodule update --init
./websrc/tools/build_and_copy_weblibs.sh websrc data/webroot/js/

# copy WSDL file
cp webservices/dss.wsdl data/webroot

# clean up release tarball

cd ..
tar cvzf dss-$DSS_RELEASE_VERSION{.tar.gz,} --exclude=\*/.git* --exclude=\*/websrc\*



# -- finally, try to build it, and let's create the documentation
set -e

rm -rf build-$DSS_RELEASE_VERSION
mkdir build-$DSS_RELEASE_VERSION
cd build-$DSS_RELEASE_VERSION
cmake ../dss-$DSS_RELEASE_VERSION -DWITH_DATADIR=../dss-$DSS_RELEASE_VERSION/data

make



echo "Building documentation for dss v$DSS_RELEASE_VERSION"

TARGET_DIR=../../dss-$DSS_RELEASE_VERSION-doc
rm -rf $TARGET_DIR
mkdir $TARGET_DIR

# JSON
echo "Running the dss now to generate json_api.xml"
./dss &
DSS_PID=$!
sleep 1
kill $DSS_PID

cd doc
cp ../../dss-$DSS_RELEASE_VERSION/doc/json_api.xslt .
xsltproc json_api.xml > $TARGET_DIR/dss-$DSS_RELEASE_VERSION-json_api.html
cp ../../dss-$DSS_RELEASE_VERSION/doc/doc.css $TARGET_DIR

# SOAP
make doc
cp webservices/html/model__soap_8h.html \
    $TARGET_DIR/dss-$DSS_RELEASE_VERSION-soap_api.html
cp webservices/html/*.css $TARGET_DIR

sed -i -e "s|model__soap_8h.html|dss-$DSS_RELEASE_VERSION-soap_api.html|g" \
    $TARGET_DIR/dss-$DSS_RELEASE_VERSION-soap_api.html
sed -i -e "s|Go to the source code of this file.||g" \
    $TARGET_DIR/dss-$DSS_RELEASE_VERSION-soap_api.html
sed -i -e "s|dss__||g" $TARGET_DIR/dss-$DSS_RELEASE_VERSION-soap_api.html

# wsdl
cp ../../dss-$DSS_RELEASE_VERSION/webservices/dss.wsdl \
    $TARGET_DIR/dss-$DSS_RELEASE_VERSION.wsdl

cd ../..
rm -r build-$DSS_RELEASE_VERSION
