#!/bin/sh
#
# DSS shell (ds3) - simple shell interface to the dss json api
# Johannes Winkelmann, johannes.winkelmann@aizo.com

APPNAME=$(basename $0)

# dss (json) login credentials
DSS_USER=dssadmin
DSS_PASS=dssadmin

# optional web server credentials, as used on the dSS11
HTTP_USER=dssadmin
HTTP_PASS=dssadmin

get_json() {
    local URL=$1
    local WRITE_COOKIES=$2
    local SILENT=$3
    local COOKIE_FILE=$4

    if [ $WRITE_COOKIES -eq 1 ]; then
	OPT="-c $COOKIE_FILE"
    else
	OPT="-b $COOKIE_FILE"
    fi

    result=$(curl $OPT -u $HTTP_USER:$HTTP_PASS -s -k $URL --digest)
    if [ $? != 0 ]; then
	echo "Could not connect to $DSS_HOST"
	exit 1
    fi

    if [ -n "$(echo $result|grep '"ok":false')" ]; then
	echo $result|sed -e 's|.*message\":\"||g' -e 's|\"}$||g'
	exit 1
    else
	if [ $SILENT -eq 1 ]; then
	     echo -n ""
	elif [ -n "$PRINT_RESULT" ]; then
	    echo $result|sed -e 's|.*,\s*||' -e 's|\s*}$|}|'
	elif [ -n "$PRINT_RAW" ]; then
	    echo $result
	fi
    fi
    return 0
}

# target, commands, args
call_dss() {
    if [ -z "$DSS_HOST" ]; then
	DSS_HOST=localhost:8080
    fi
    local URL=https://$DSS_HOST/json/$1/$2
    local LOGIN_URL=https://$DSS_HOST/json/system
    shift; shift

    if [ -n "$1" ]; then
	URL="$URL?$1"
	shift
    fi
    while [ -n "$1" ]; do
	URL="$URL&$1"
	shift
    done

    local COOKIE_FILE=$(mktemp -t ds3XXX)
    get_json "$LOGIN_URL/login?user=$DSS_USER&password=$DSS_PASS" 1 1 $COOKIE_FILE
    get_json $URL 0 0 $COOKIE_FILE
    get_json "$LOGIN_URL/logout" 0 1 $COOKIE_FILE

    rm $COOKIE_FILE
}

usage() {

    if [ -n "$1" ]; then
	echo "Usage: $APPNAME $target $target_command $*"
    else
	if [ -n "$target_command" ]; then
	    echo "Unknown target/command combination"
	elif [ -n "$target" ]; then
	    echo "Command missing for target '$target'"
	fi
	
	echo "Usage: $APPNAME <target> <command> <args>"
    fi
    echo ""
    echo "Supported commands:"
    echo "  device:"
    echo "    turnOn, turnOff, getState, getName, getConsumption | <dsid>"
    echo "    setName | <dsid> <new name>"
    echo "  Example: $APPNAME device getState 3504175fe0000000000012e7"
    echo ""
    echo "  zone:"
    echo "    turnOn, turnOff, increaseValue, decreaseValue | <zone id> <group id>"
    echo "    callScene | <zone id> <scene #> <group id>"
    echo "  Example: $APPNAME zone turnOn 172"
    echo ""
    echo "  apartment"
    echo "    turnOn, turnOff, getName, getConsumption, increaseValue, decreaseValue, rescan"
    echo "    callScene | <scene #>"
    echo "    setName | <new name>"
    echo "  Example: $APPNAME apartment callScene 5"
}

fatal_usage() {
    usage $*
    exit 1
}

command="$1_$2"
target=$1
target_command=$2
shift; shift

case "$command" in
    ###
    ## device commands
    #
    "device_turnOn"|"device_turnOff"|\
	"device_increaseValue"|"device_decreaseValue"|\
	"device_startDim"|"device_endDim")
         call_dss "device" "$target_command" "dsid=$1"
	 ;;
    "device_getState"|"device_getName"|"device_getConsumption")
         PRINT_RESULT="yes" call_dss "device" "$target_command" "dsid=$1"
	 ;;
    "device_setName")
         call_dss "device" "$target_command" "dsid=$1" "newName=$2"
	 ;;

    ###
    ## zone commands
    #
    "zone_turnOn"|"zone_turnOff"|\
    "apartment_increaseValue"|"apartment_decreaseValue")
        [ -z "$2" ] && fatal_usage "<zoneid> <group id>"
        call_dss "$target" "$target_command" "id=$1" "groupID=$2"
	;;
    "zone_callScene")
        [ -z "$3" ] && fatal_usage "<zoneid> <scene#> <group id>"
        call_dss "$target" "$target_command" "id=$1" "sceneNumber=$2" "groupID=$3"
	;;
    "zone_getConsumption")
        PRINT_RESULT="yes" call_dss "$target" "$target_command" "id=$1" "sceneNumber=$2"
	;;

    ###
    ## apartment
    #
    "apartment_turnOn"|"apartment_turnOff")
        [ -z "$1" ] && fatal_usage "<group id>"
        call_dss "$target" "$target_command" "groupID=$1"
	;;
    "apartment_callScene")
        [ -z "$2" ] && fatal_usage "<scene#> <group id>"
        call_dss "$target" "$target_command" "sceneNumber=$1" "groupID=$2"
	;;
    "apartment_getName"|"apartment_getConsumption"|\
    "apartment_increaseValue"|"apartment_decreaseValue"|\
    "apartment_rescan")
        PRINT_RESULT="yes" call_dss "$target" "$target_command"
	;;
    "apartment_getStructure"|"apartment_getDevices")
        PRINT_RAW="yes" call_dss "$target" "$target_command"
	;;
    "apartment_setName")
        call_dss "$target" "$target_command" "newName=$1"
	;;

    ###
    ## event
    #
    "event_raise")
        [ -z "$1" ] && fatal_usage "<event name>"
        call_dss "$target" "$target_command" "name=$1"
	;;

    ###
    ## system
    #
    "system_version")
        PRINT_RESULT="yes" call_dss "$target" "$target_command"
	;;
    *)
        fatal_usage
	;;
esac

exit 0
