#!/bin/bash
#
# DSS shell (ds3) - simple shell interface to the dss json api
# Johannes Winkelmann, johannes.winkelmann@aizo.com

APPNAME=$(basename $0)

# target, commands, args
function call_dss() {
    if [ -z "$DSS_HOST" ]; then
	DSS_HOST=localhost
    fi
    URL=http://$DSS_HOST:8080/json/$1/$2
    shift; shift

    if [ -n "$1" ]; then
	URL="$URL?$1"
	shift
    fi
    while [ -n "$1" ]; do
	URL="$URL&$1"
	shift
    done
    
    result=$(wget -q -O - $URL)
    if [ -n "$(echo $result|grep '"ok":false')" ]; then
	echo $result|sed -e 's|.*message\":\"||g' -e 's|\"}$||g'
	exit 1
    else
	if [ -n "$PRINT_RESULT" ]; then
	    echo $result|sed -e 's|.*,\s*||' -e 's|\s*}$||'
	fi
    fi
    return 0
}

usage() {
    if [ -n "$target_command" ]; then
	echo "Unknown target/command combination"
    elif [ -n "$target" ]; then
	echo "Command missing for target '$target'"
    fi
    echo "Usage: $APPNAME <target> <command> <args>"
    echo ""
    echo "Supported commands:"
    echo "  device:"
    echo "    turnOn, turnOff, getState, getName, getConsumption | <dsid>"
    echo "    setName | <dsid> <new name>"
    echo "  Example: $APPNAME device getState 3504175fe0000000000012e7"
    echo ""
    echo "  zone:"
    echo "    turnOn, turnOff | <zone id>"
    echo "    callScene | <zone id> <scene #>"
    echo "  Example: $APPNAME zone turnOn 172"
    echo ""
    echo "  apartment"
    echo "    turnOn, turnOff, getName, getConsumption"
    echo "    callScene | <scene #>"
    echo "    setName | <new name>"
    echo "  Example: $APPNAME apartment callScene 5"
}

command="$1_$2"
target=$1
target_command=$2
shift; shift

case "$command" in
    ###
    ## device commands
    #
    "device_turnOn"|"device_turnOff")
         call_dss "device" "$target_command" "dsid=$1"
	 ;;
    "device_getState"|"device_getName"|"device_getConsumption")
         PRINT_RESULT="yes" call_dss "device" "$target_command" "dsid=$1"
	 ;;
    "device_setName")
         call_dss "device" "$target_command" "dsid=$1" "newName=$2"
	 ;;

    ###
    ## zone commands
    #
    "zone_turnOn"|"zone_turnOff")
        call_dss "$target" "$target_command" "id=$1"
	;;
    "zone_callScene")
        call_dss "$target" "$target_command" "id=$1" "sceneNr=$2"
	;;
    "zone_getConsumption")
        PRINT_RESULT="yes" call_dss "$target" "$target_command" "id=$1" "sceneNr=$2"
	;;

    ###
    ## apartment
    #
    "apartment_turnOn"|"apartment_turnOff")
        call_dss "$target" "$target_command"
	;;
    "apartment_callScene")
        call_dss "$target" "$target_command" "sceneNr=$1"
	;;
    "apartment_getName"|"apartment_getConsumption")
        PRINT_RESULT="yes" call_dss "$target" "$target_command"
	;;
    "apartment_setName")
        call_dss "$target" "$target_command" "newName=$1"
	;;

    ###
    ## system
    #
    "system_version")
        PRINT_RESULT="yes" call_dss "$target" "$target_command"
	;;
    *)
        usage
	exit 1
	;;
esac

exit 0
