/* soapStub.h
   Generated by gSOAP 2.7.10 from model_soap.h
   Copyright(C) 2000-2008, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef soapStub_H
#define soapStub_H
#include "stdsoap2.h"

/******************************************************************************\
 *                                                                            *
 * Enumerations                                                               *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Classes and Structs                                                        *
 *                                                                            *
\******************************************************************************/


#if 0 /* volatile type: do not redeclare here */

#endif

#ifndef SOAP_TYPE_IntArray
#define SOAP_TYPE_IntArray (11)
/* SOAP encoded array of xsd:unsignedInt schema type: */
class SOAP_CMAC IntArray
{
public:
	unsigned long *__ptr;
	int __size;
public:
	virtual int soap_type() const { return 11; } /* = unique id SOAP_TYPE_IntArray */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         IntArray() : __ptr(NULL), __size(0) { }
	virtual ~IntArray() { }
};
#endif

#ifndef SOAP_TYPE_StringArray
#define SOAP_TYPE_StringArray (13)
/* SOAP encoded array of xsd:string schema type: */
class SOAP_CMAC StringArray
{
public:
	char **__ptr;
	int __size;
public:
	virtual int soap_type() const { return 13; } /* = unique id SOAP_TYPE_StringArray */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         StringArray() : __ptr(NULL), __size(0) { }
	virtual ~StringArray() { }
};
#endif

#ifndef SOAP_TYPE_dss__AuthenticateResponse
#define SOAP_TYPE_dss__AuthenticateResponse (17)
/* dss:AuthenticateResponse */
struct dss__AuthenticateResponse
{
public:
	int token;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Authenticate
#define SOAP_TYPE_dss__Authenticate (18)
/* dss:Authenticate */
struct dss__Authenticate
{
public:
	char *_userName;	/* optional element of type xsd:string */
	char *_password;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_dss__SignOffResponse
#define SOAP_TYPE_dss__SignOffResponse (20)
/* dss:SignOffResponse */
struct dss__SignOffResponse
{
public:
	int result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__SignOff
#define SOAP_TYPE_dss__SignOff (21)
/* dss:SignOff */
struct dss__SignOff
{
public:
	int _token;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__FreeSetResponse
#define SOAP_TYPE_dss__FreeSetResponse (25)
/* dss:FreeSetResponse */
struct dss__FreeSetResponse
{
public:
	bool result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:boolean */
};
#endif

#ifndef SOAP_TYPE_dss__FreeSet
#define SOAP_TYPE_dss__FreeSet (26)
/* dss:FreeSet */
struct dss__FreeSet
{
public:
	int _token;	/* required element of type xsd:int */
	int _setID;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Apartment_CreateSetFromGroupResponse
#define SOAP_TYPE_dss__Apartment_CreateSetFromGroupResponse (28)
/* dss:Apartment-CreateSetFromGroupResponse */
struct dss__Apartment_CreateSetFromGroupResponse
{
public:
	int setID;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Apartment_CreateSetFromGroup
#define SOAP_TYPE_dss__Apartment_CreateSetFromGroup (29)
/* dss:Apartment-CreateSetFromGroup */
struct dss__Apartment_CreateSetFromGroup
{
public:
	int _token;	/* required element of type xsd:int */
	char *_groupName;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_dss__Apartment_CreateSetFromDeviceIDsResponse
#define SOAP_TYPE_dss__Apartment_CreateSetFromDeviceIDsResponse (31)
/* dss:Apartment-CreateSetFromDeviceIDsResponse */
struct dss__Apartment_CreateSetFromDeviceIDsResponse
{
public:
	int setID;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Apartment_CreateSetFromDeviceIDs
#define SOAP_TYPE_dss__Apartment_CreateSetFromDeviceIDs (32)
/* dss:Apartment-CreateSetFromDeviceIDs */
struct dss__Apartment_CreateSetFromDeviceIDs
{
public:
	int _token;	/* required element of type xsd:int */
	IntArray _ids;	/* required element of type ArrayOfunsignedInt */
};
#endif

#ifndef SOAP_TYPE_dss__Apartment_CreateSetFromDeviceNamesResponse
#define SOAP_TYPE_dss__Apartment_CreateSetFromDeviceNamesResponse (34)
/* dss:Apartment-CreateSetFromDeviceNamesResponse */
struct dss__Apartment_CreateSetFromDeviceNamesResponse
{
public:
	int setID;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Apartment_CreateSetFromDeviceNames
#define SOAP_TYPE_dss__Apartment_CreateSetFromDeviceNames (35)
/* dss:Apartment-CreateSetFromDeviceNames */
struct dss__Apartment_CreateSetFromDeviceNames
{
public:
	int _token;	/* required element of type xsd:int */
	StringArray _names;	/* required element of type ArrayOfstring */
};
#endif

#ifndef SOAP_TYPE_dss__Apartment_CreateEmptySetResponse
#define SOAP_TYPE_dss__Apartment_CreateEmptySetResponse (37)
/* dss:Apartment-CreateEmptySetResponse */
struct dss__Apartment_CreateEmptySetResponse
{
public:
	int setID;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Apartment_CreateEmptySet
#define SOAP_TYPE_dss__Apartment_CreateEmptySet (38)
/* dss:Apartment-CreateEmptySet */
struct dss__Apartment_CreateEmptySet
{
public:
	int _token;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Apartment_GetDevicesResponse
#define SOAP_TYPE_dss__Apartment_GetDevicesResponse (40)
/* dss:Apartment-GetDevicesResponse */
struct dss__Apartment_GetDevicesResponse
{
public:
	int setID;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Apartment_GetDevices
#define SOAP_TYPE_dss__Apartment_GetDevices (41)
/* dss:Apartment-GetDevices */
struct dss__Apartment_GetDevices
{
public:
	int _token;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Apartment_GetDeviceIDByNameResponse
#define SOAP_TYPE_dss__Apartment_GetDeviceIDByNameResponse (43)
/* dss:Apartment-GetDeviceIDByNameResponse */
struct dss__Apartment_GetDeviceIDByNameResponse
{
public:
	int deviceID;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Apartment_GetDeviceIDByName
#define SOAP_TYPE_dss__Apartment_GetDeviceIDByName (44)
/* dss:Apartment-GetDeviceIDByName */
struct dss__Apartment_GetDeviceIDByName
{
public:
	int _token;	/* required element of type xsd:int */
	char *_deviceName;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_dss__Set_AddDeviceByNameResponse
#define SOAP_TYPE_dss__Set_AddDeviceByNameResponse (46)
/* dss:Set-AddDeviceByNameResponse */
struct dss__Set_AddDeviceByNameResponse
{
public:
	bool result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:boolean */
};
#endif

#ifndef SOAP_TYPE_dss__Set_AddDeviceByName
#define SOAP_TYPE_dss__Set_AddDeviceByName (47)
/* dss:Set-AddDeviceByName */
struct dss__Set_AddDeviceByName
{
public:
	int _token;	/* required element of type xsd:int */
	int _setID;	/* required element of type xsd:int */
	char *_name;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_dss__Set_AddDeviceByIDResponse
#define SOAP_TYPE_dss__Set_AddDeviceByIDResponse (49)
/* dss:Set-AddDeviceByIDResponse */
struct dss__Set_AddDeviceByIDResponse
{
public:
	bool result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:boolean */
};
#endif

#ifndef SOAP_TYPE_dss__Set_AddDeviceByID
#define SOAP_TYPE_dss__Set_AddDeviceByID (50)
/* dss:Set-AddDeviceByID */
struct dss__Set_AddDeviceByID
{
public:
	int _token;	/* required element of type xsd:int */
	int _setID;	/* required element of type xsd:int */
	int _deviceID;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Set_RemoveDeviceResponse
#define SOAP_TYPE_dss__Set_RemoveDeviceResponse (52)
/* dss:Set-RemoveDeviceResponse */
struct dss__Set_RemoveDeviceResponse
{
public:
	bool result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:boolean */
};
#endif

#ifndef SOAP_TYPE_dss__Set_RemoveDevice
#define SOAP_TYPE_dss__Set_RemoveDevice (53)
/* dss:Set-RemoveDevice */
struct dss__Set_RemoveDevice
{
public:
	int _token;	/* required element of type xsd:int */
	int _setID;	/* required element of type xsd:int */
	int _deviceID;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Set_CombineResponse
#define SOAP_TYPE_dss__Set_CombineResponse (55)
/* dss:Set-CombineResponse */
struct dss__Set_CombineResponse
{
public:
	int setID;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Set_Combine
#define SOAP_TYPE_dss__Set_Combine (56)
/* dss:Set-Combine */
struct dss__Set_Combine
{
public:
	int _token;	/* required element of type xsd:int */
	int _setID1;	/* required element of type xsd:int */
	int _setID2;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Set_RemoveResponse
#define SOAP_TYPE_dss__Set_RemoveResponse (58)
/* dss:Set-RemoveResponse */
struct dss__Set_RemoveResponse
{
public:
	int setID;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Set_Remove
#define SOAP_TYPE_dss__Set_Remove (59)
/* dss:Set-Remove */
struct dss__Set_Remove
{
public:
	int _token;	/* required element of type xsd:int */
	int _setID;	/* required element of type xsd:int */
	int _setIDToRemove;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Set_ByGroupResponse
#define SOAP_TYPE_dss__Set_ByGroupResponse (61)
/* dss:Set-ByGroupResponse */
struct dss__Set_ByGroupResponse
{
public:
	int setID;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Set_ByGroup
#define SOAP_TYPE_dss__Set_ByGroup (62)
/* dss:Set-ByGroup */
struct dss__Set_ByGroup
{
public:
	int _token;	/* required element of type xsd:int */
	int _setID;	/* required element of type xsd:int */
	int _groupID;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Set_GetContainedDevicesResponse
#define SOAP_TYPE_dss__Set_GetContainedDevicesResponse (65)
/* dss:Set-GetContainedDevicesResponse */
struct dss__Set_GetContainedDevicesResponse
{
public:
	IntArray deviceIDs;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type ArrayOfunsignedInt */
};
#endif

#ifndef SOAP_TYPE_dss__Set_GetContainedDevices
#define SOAP_TYPE_dss__Set_GetContainedDevices (66)
/* dss:Set-GetContainedDevices */
struct dss__Set_GetContainedDevices
{
public:
	int _token;	/* required element of type xsd:int */
	int _setID;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Apartment_GetGroupByNameResponse
#define SOAP_TYPE_dss__Apartment_GetGroupByNameResponse (68)
/* dss:Apartment-GetGroupByNameResponse */
struct dss__Apartment_GetGroupByNameResponse
{
public:
	int groupID;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Apartment_GetGroupByName
#define SOAP_TYPE_dss__Apartment_GetGroupByName (69)
/* dss:Apartment-GetGroupByName */
struct dss__Apartment_GetGroupByName
{
public:
	int _token;	/* required element of type xsd:int */
	char *_groupName;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_dss__Apartment_GetRoomByNameResponse
#define SOAP_TYPE_dss__Apartment_GetRoomByNameResponse (71)
/* dss:Apartment-GetRoomByNameResponse */
struct dss__Apartment_GetRoomByNameResponse
{
public:
	int roomID;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Apartment_GetRoomByName
#define SOAP_TYPE_dss__Apartment_GetRoomByName (72)
/* dss:Apartment-GetRoomByName */
struct dss__Apartment_GetRoomByName
{
public:
	int _token;	/* required element of type xsd:int */
	char *_roomName;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_dss__Apartment_GetRoomIDsResponse
#define SOAP_TYPE_dss__Apartment_GetRoomIDsResponse (74)
/* dss:Apartment-GetRoomIDsResponse */
struct dss__Apartment_GetRoomIDsResponse
{
public:
	IntArray roomIDs;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type ArrayOfunsignedInt */
};
#endif

#ifndef SOAP_TYPE_dss__Apartment_GetRoomIDs
#define SOAP_TYPE_dss__Apartment_GetRoomIDs (75)
/* dss:Apartment-GetRoomIDs */
struct dss__Apartment_GetRoomIDs
{
public:
	int _token;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Set_TurnOnResponse
#define SOAP_TYPE_dss__Set_TurnOnResponse (77)
/* dss:Set-TurnOnResponse */
struct dss__Set_TurnOnResponse
{
public:
	bool result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:boolean */
};
#endif

#ifndef SOAP_TYPE_dss__Set_TurnOn
#define SOAP_TYPE_dss__Set_TurnOn (78)
/* dss:Set-TurnOn */
struct dss__Set_TurnOn
{
public:
	int _token;	/* required element of type xsd:int */
	int _setID;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Set_TurnOffResponse
#define SOAP_TYPE_dss__Set_TurnOffResponse (80)
/* dss:Set-TurnOffResponse */
struct dss__Set_TurnOffResponse
{
public:
	bool result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:boolean */
};
#endif

#ifndef SOAP_TYPE_dss__Set_TurnOff
#define SOAP_TYPE_dss__Set_TurnOff (81)
/* dss:Set-TurnOff */
struct dss__Set_TurnOff
{
public:
	int _token;	/* required element of type xsd:int */
	int _setID;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Set_IncreaseValueResponse
#define SOAP_TYPE_dss__Set_IncreaseValueResponse (83)
/* dss:Set-IncreaseValueResponse */
struct dss__Set_IncreaseValueResponse
{
public:
	bool result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:boolean */
};
#endif

#ifndef SOAP_TYPE_dss__Set_IncreaseValue
#define SOAP_TYPE_dss__Set_IncreaseValue (84)
/* dss:Set-IncreaseValue */
struct dss__Set_IncreaseValue
{
public:
	int _token;	/* required element of type xsd:int */
	int _setID;	/* required element of type xsd:int */
	int _paramID;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Set_DecreaseValueResponse
#define SOAP_TYPE_dss__Set_DecreaseValueResponse (86)
/* dss:Set-DecreaseValueResponse */
struct dss__Set_DecreaseValueResponse
{
public:
	bool result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:boolean */
};
#endif

#ifndef SOAP_TYPE_dss__Set_DecreaseValue
#define SOAP_TYPE_dss__Set_DecreaseValue (87)
/* dss:Set-DecreaseValue */
struct dss__Set_DecreaseValue
{
public:
	int _token;	/* required element of type xsd:int */
	int _setID;	/* required element of type xsd:int */
	int _paramID;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Set_EnableResponse
#define SOAP_TYPE_dss__Set_EnableResponse (89)
/* dss:Set-EnableResponse */
struct dss__Set_EnableResponse
{
public:
	bool result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:boolean */
};
#endif

#ifndef SOAP_TYPE_dss__Set_Enable
#define SOAP_TYPE_dss__Set_Enable (90)
/* dss:Set-Enable */
struct dss__Set_Enable
{
public:
	int _token;	/* required element of type xsd:int */
	int _setID;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Set_DisableResponse
#define SOAP_TYPE_dss__Set_DisableResponse (92)
/* dss:Set-DisableResponse */
struct dss__Set_DisableResponse
{
public:
	bool result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:boolean */
};
#endif

#ifndef SOAP_TYPE_dss__Set_Disable
#define SOAP_TYPE_dss__Set_Disable (93)
/* dss:Set-Disable */
struct dss__Set_Disable
{
public:
	int _token;	/* required element of type xsd:int */
	int _setID;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Set_StartDimResponse
#define SOAP_TYPE_dss__Set_StartDimResponse (95)
/* dss:Set-StartDimResponse */
struct dss__Set_StartDimResponse
{
public:
	bool result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:boolean */
};
#endif

#ifndef SOAP_TYPE_dss__Set_StartDim
#define SOAP_TYPE_dss__Set_StartDim (96)
/* dss:Set-StartDim */
struct dss__Set_StartDim
{
public:
	int _token;	/* required element of type xsd:int */
	int _setID;	/* required element of type xsd:int */
	bool _directionUp;	/* required element of type xsd:boolean */
	int _paramID;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Set_EndDimResponse
#define SOAP_TYPE_dss__Set_EndDimResponse (98)
/* dss:Set-EndDimResponse */
struct dss__Set_EndDimResponse
{
public:
	bool result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:boolean */
};
#endif

#ifndef SOAP_TYPE_dss__Set_EndDim
#define SOAP_TYPE_dss__Set_EndDim (99)
/* dss:Set-EndDim */
struct dss__Set_EndDim
{
public:
	int _token;	/* required element of type xsd:int */
	int _setID;	/* required element of type xsd:int */
	int _paramID;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Set_SetValueResponse
#define SOAP_TYPE_dss__Set_SetValueResponse (102)
/* dss:Set-SetValueResponse */
struct dss__Set_SetValueResponse
{
public:
	bool result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:boolean */
};
#endif

#ifndef SOAP_TYPE_dss__Set_SetValue
#define SOAP_TYPE_dss__Set_SetValue (103)
/* dss:Set-SetValue */
struct dss__Set_SetValue
{
public:
	int _token;	/* required element of type xsd:int */
	int _setID;	/* required element of type xsd:int */
	double _value;	/* required element of type xsd:double */
	int _paramID;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Device_TurnOnResponse
#define SOAP_TYPE_dss__Device_TurnOnResponse (105)
/* dss:Device-TurnOnResponse */
struct dss__Device_TurnOnResponse
{
public:
	bool result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:boolean */
};
#endif

#ifndef SOAP_TYPE_dss__Device_TurnOn
#define SOAP_TYPE_dss__Device_TurnOn (106)
/* dss:Device-TurnOn */
struct dss__Device_TurnOn
{
public:
	int _token;	/* required element of type xsd:int */
	unsigned long _deviceID;	/* required element of type xsd:unsignedInt */
};
#endif

#ifndef SOAP_TYPE_dss__Device_TurnOffResponse
#define SOAP_TYPE_dss__Device_TurnOffResponse (108)
/* dss:Device-TurnOffResponse */
struct dss__Device_TurnOffResponse
{
public:
	bool result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:boolean */
};
#endif

#ifndef SOAP_TYPE_dss__Device_TurnOff
#define SOAP_TYPE_dss__Device_TurnOff (109)
/* dss:Device-TurnOff */
struct dss__Device_TurnOff
{
public:
	int _token;	/* required element of type xsd:int */
	unsigned long _deviceID;	/* required element of type xsd:unsignedInt */
};
#endif

#ifndef SOAP_TYPE_dss__Device_IncreaseValueResponse
#define SOAP_TYPE_dss__Device_IncreaseValueResponse (111)
/* dss:Device-IncreaseValueResponse */
struct dss__Device_IncreaseValueResponse
{
public:
	bool result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:boolean */
};
#endif

#ifndef SOAP_TYPE_dss__Device_IncreaseValue
#define SOAP_TYPE_dss__Device_IncreaseValue (112)
/* dss:Device-IncreaseValue */
struct dss__Device_IncreaseValue
{
public:
	int _token;	/* required element of type xsd:int */
	unsigned long _deviceID;	/* required element of type xsd:unsignedInt */
	int _paramID;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Device_DecreaseValueResponse
#define SOAP_TYPE_dss__Device_DecreaseValueResponse (114)
/* dss:Device-DecreaseValueResponse */
struct dss__Device_DecreaseValueResponse
{
public:
	bool result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:boolean */
};
#endif

#ifndef SOAP_TYPE_dss__Device_DecreaseValue
#define SOAP_TYPE_dss__Device_DecreaseValue (115)
/* dss:Device-DecreaseValue */
struct dss__Device_DecreaseValue
{
public:
	int _token;	/* required element of type xsd:int */
	unsigned long _deviceID;	/* required element of type xsd:unsignedInt */
	int _paramID;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Device_EnableResponse
#define SOAP_TYPE_dss__Device_EnableResponse (117)
/* dss:Device-EnableResponse */
struct dss__Device_EnableResponse
{
public:
	bool result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:boolean */
};
#endif

#ifndef SOAP_TYPE_dss__Device_Enable
#define SOAP_TYPE_dss__Device_Enable (118)
/* dss:Device-Enable */
struct dss__Device_Enable
{
public:
	int _token;	/* required element of type xsd:int */
	unsigned long _deviceID;	/* required element of type xsd:unsignedInt */
};
#endif

#ifndef SOAP_TYPE_dss__Device_DisableResponse
#define SOAP_TYPE_dss__Device_DisableResponse (120)
/* dss:Device-DisableResponse */
struct dss__Device_DisableResponse
{
public:
	bool result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:boolean */
};
#endif

#ifndef SOAP_TYPE_dss__Device_Disable
#define SOAP_TYPE_dss__Device_Disable (121)
/* dss:Device-Disable */
struct dss__Device_Disable
{
public:
	int _token;	/* required element of type xsd:int */
	unsigned long _deviceID;	/* required element of type xsd:unsignedInt */
};
#endif

#ifndef SOAP_TYPE_dss__Device_StartDimResponse
#define SOAP_TYPE_dss__Device_StartDimResponse (123)
/* dss:Device-StartDimResponse */
struct dss__Device_StartDimResponse
{
public:
	bool result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:boolean */
};
#endif

#ifndef SOAP_TYPE_dss__Device_StartDim
#define SOAP_TYPE_dss__Device_StartDim (124)
/* dss:Device-StartDim */
struct dss__Device_StartDim
{
public:
	int _token;	/* required element of type xsd:int */
	unsigned long _deviceID;	/* required element of type xsd:unsignedInt */
	bool _directionUp;	/* required element of type xsd:boolean */
	int _paramID;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Device_EndDimResponse
#define SOAP_TYPE_dss__Device_EndDimResponse (126)
/* dss:Device-EndDimResponse */
struct dss__Device_EndDimResponse
{
public:
	bool result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:boolean */
};
#endif

#ifndef SOAP_TYPE_dss__Device_EndDim
#define SOAP_TYPE_dss__Device_EndDim (127)
/* dss:Device-EndDim */
struct dss__Device_EndDim
{
public:
	int _token;	/* required element of type xsd:int */
	unsigned long _deviceID;	/* required element of type xsd:unsignedInt */
	int _paramID;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Device_SetValueResponse
#define SOAP_TYPE_dss__Device_SetValueResponse (129)
/* dss:Device-SetValueResponse */
struct dss__Device_SetValueResponse
{
public:
	bool result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:boolean */
};
#endif

#ifndef SOAP_TYPE_dss__Device_SetValue
#define SOAP_TYPE_dss__Device_SetValue (130)
/* dss:Device-SetValue */
struct dss__Device_SetValue
{
public:
	int _token;	/* required element of type xsd:int */
	unsigned long _deviceID;	/* required element of type xsd:unsignedInt */
	double _value;	/* required element of type xsd:double */
	int _paramID;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Device_GetValueResponse
#define SOAP_TYPE_dss__Device_GetValueResponse (133)
/* dss:Device-GetValueResponse */
struct dss__Device_GetValueResponse
{
public:
	double result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:double */
};
#endif

#ifndef SOAP_TYPE_dss__Device_GetValue
#define SOAP_TYPE_dss__Device_GetValue (134)
/* dss:Device-GetValue */
struct dss__Device_GetValue
{
public:
	int _token;	/* required element of type xsd:int */
	unsigned long _deviceID;	/* required element of type xsd:unsignedInt */
	int _paramID;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Device_GetNameResponse
#define SOAP_TYPE_dss__Device_GetNameResponse (136)
/* dss:Device-GetNameResponse */
struct dss__Device_GetNameResponse
{
public:
	char **result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_dss__Device_GetName
#define SOAP_TYPE_dss__Device_GetName (137)
/* dss:Device-GetName */
struct dss__Device_GetName
{
public:
	int _token;	/* required element of type xsd:int */
	unsigned long _deviceID;	/* required element of type xsd:unsignedInt */
};
#endif

#ifndef SOAP_TYPE_dss__Device_GetRoomIDResponse
#define SOAP_TYPE_dss__Device_GetRoomIDResponse (139)
/* dss:Device-GetRoomIDResponse */
struct dss__Device_GetRoomIDResponse
{
public:
	int result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Device_GetRoomID
#define SOAP_TYPE_dss__Device_GetRoomID (140)
/* dss:Device-GetRoomID */
struct dss__Device_GetRoomID
{
public:
	int _token;	/* required element of type xsd:int */
	unsigned long _deviceID;	/* required element of type xsd:unsignedInt */
};
#endif

#ifndef SOAP_TYPE_dss__Device_GetDSIDResponse
#define SOAP_TYPE_dss__Device_GetDSIDResponse (143)
/* dss:Device-GetDSIDResponse */
struct dss__Device_GetDSIDResponse
{
public:
	unsigned long result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:unsignedInt */
};
#endif

#ifndef SOAP_TYPE_dss__Device_GetDSID
#define SOAP_TYPE_dss__Device_GetDSID (144)
/* dss:Device-GetDSID */
struct dss__Device_GetDSID
{
public:
	int _token;	/* required element of type xsd:int */
	unsigned long _deviceID;	/* required element of type xsd:unsignedInt */
};
#endif

#ifndef SOAP_TYPE_dss__Apartment_GetModulatorIDsResponse
#define SOAP_TYPE_dss__Apartment_GetModulatorIDsResponse (146)
/* dss:Apartment-GetModulatorIDsResponse */
struct dss__Apartment_GetModulatorIDsResponse
{
public:
	IntArray ids;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type ArrayOfunsignedInt */
};
#endif

#ifndef SOAP_TYPE_dss__Apartment_GetModulatorIDs
#define SOAP_TYPE_dss__Apartment_GetModulatorIDs (147)
/* dss:Apartment-GetModulatorIDs */
struct dss__Apartment_GetModulatorIDs
{
public:
	int _token;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Modulator_GetDSIDResponse
#define SOAP_TYPE_dss__Modulator_GetDSIDResponse (149)
/* dss:Modulator-GetDSIDResponse */
struct dss__Modulator_GetDSIDResponse
{
public:
	unsigned long dsid;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:unsignedInt */
};
#endif

#ifndef SOAP_TYPE_dss__Modulator_GetDSID
#define SOAP_TYPE_dss__Modulator_GetDSID (150)
/* dss:Modulator-GetDSID */
struct dss__Modulator_GetDSID
{
public:
	int _token;	/* required element of type xsd:int */
	int _modulatorID;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Modulator_GetNameResponse
#define SOAP_TYPE_dss__Modulator_GetNameResponse (152)
/* dss:Modulator-GetNameResponse */
struct dss__Modulator_GetNameResponse
{
public:
	char **name;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_dss__Modulator_GetName
#define SOAP_TYPE_dss__Modulator_GetName (153)
/* dss:Modulator-GetName */
struct dss__Modulator_GetName
{
public:
	int _token;	/* required element of type xsd:int */
	int _modulatorID;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Apartment_AllocateRoomResponse
#define SOAP_TYPE_dss__Apartment_AllocateRoomResponse (155)
/* dss:Apartment-AllocateRoomResponse */
struct dss__Apartment_AllocateRoomResponse
{
public:
	int roomID;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Apartment_AllocateRoom
#define SOAP_TYPE_dss__Apartment_AllocateRoom (156)
/* dss:Apartment-AllocateRoom */
struct dss__Apartment_AllocateRoom
{
public:
	int _token;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Apartment_DeleteRoomResponse
#define SOAP_TYPE_dss__Apartment_DeleteRoomResponse (158)
/* dss:Apartment-DeleteRoomResponse */
struct dss__Apartment_DeleteRoomResponse
{
public:
	int result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Apartment_DeleteRoom
#define SOAP_TYPE_dss__Apartment_DeleteRoom (159)
/* dss:Apartment-DeleteRoom */
struct dss__Apartment_DeleteRoom
{
public:
	int _token;	/* required element of type xsd:int */
	int _roomID;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Room_AddDeviceResponse
#define SOAP_TYPE_dss__Room_AddDeviceResponse (161)
/* dss:Room-AddDeviceResponse */
struct dss__Room_AddDeviceResponse
{
public:
	int result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Room_AddDevice
#define SOAP_TYPE_dss__Room_AddDevice (162)
/* dss:Room-AddDevice */
struct dss__Room_AddDevice
{
public:
	int _token;	/* required element of type xsd:int */
	int _roomID;	/* required element of type xsd:int */
	int _deviceID;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Room_RemoveDeviceResponse
#define SOAP_TYPE_dss__Room_RemoveDeviceResponse (164)
/* dss:Room-RemoveDeviceResponse */
struct dss__Room_RemoveDeviceResponse
{
public:
	int result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Room_RemoveDevice
#define SOAP_TYPE_dss__Room_RemoveDevice (165)
/* dss:Room-RemoveDevice */
struct dss__Room_RemoveDevice
{
public:
	int _token;	/* required element of type xsd:int */
	int _roomID;	/* required element of type xsd:int */
	int _deviceID;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Room_SetNameResponse
#define SOAP_TYPE_dss__Room_SetNameResponse (167)
/* dss:Room-SetNameResponse */
struct dss__Room_SetNameResponse
{
public:
	int result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Room_SetName
#define SOAP_TYPE_dss__Room_SetName (168)
/* dss:Room-SetName */
struct dss__Room_SetName
{
public:
	int _token;	/* required element of type xsd:int */
	int _roomID;	/* required element of type xsd:int */
	char *_name;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_dss__Apartment_AllocateUserGroupResponse
#define SOAP_TYPE_dss__Apartment_AllocateUserGroupResponse (170)
/* dss:Apartment-AllocateUserGroupResponse */
struct dss__Apartment_AllocateUserGroupResponse
{
public:
	int groupID;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Apartment_AllocateUserGroup
#define SOAP_TYPE_dss__Apartment_AllocateUserGroup (171)
/* dss:Apartment-AllocateUserGroup */
struct dss__Apartment_AllocateUserGroup
{
public:
	int _token;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Group_RemoveUserGroupResponse
#define SOAP_TYPE_dss__Group_RemoveUserGroupResponse (173)
/* dss:Group-RemoveUserGroupResponse */
struct dss__Group_RemoveUserGroupResponse
{
public:
	int result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Group_RemoveUserGroup
#define SOAP_TYPE_dss__Group_RemoveUserGroup (174)
/* dss:Group-RemoveUserGroup */
struct dss__Group_RemoveUserGroup
{
public:
	int _token;	/* required element of type xsd:int */
	int _groupID;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Group_AddDeviceResponse
#define SOAP_TYPE_dss__Group_AddDeviceResponse (176)
/* dss:Group-AddDeviceResponse */
struct dss__Group_AddDeviceResponse
{
public:
	int result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Group_AddDevice
#define SOAP_TYPE_dss__Group_AddDevice (177)
/* dss:Group-AddDevice */
struct dss__Group_AddDevice
{
public:
	int _token;	/* required element of type xsd:int */
	int _groupID;	/* required element of type xsd:int */
	int _deviceID;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Group_RemoveDeviceResponse
#define SOAP_TYPE_dss__Group_RemoveDeviceResponse (179)
/* dss:Group-RemoveDeviceResponse */
struct dss__Group_RemoveDeviceResponse
{
public:
	int result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Group_RemoveDevice
#define SOAP_TYPE_dss__Group_RemoveDevice (180)
/* dss:Group-RemoveDevice */
struct dss__Group_RemoveDevice
{
public:
	int _token;	/* required element of type xsd:int */
	int _groupID;	/* required element of type xsd:int */
	int _deviceID;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Device_GetFunctionIDResponse
#define SOAP_TYPE_dss__Device_GetFunctionIDResponse (182)
/* dss:Device-GetFunctionIDResponse */
struct dss__Device_GetFunctionIDResponse
{
public:
	int result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Device_GetFunctionID
#define SOAP_TYPE_dss__Device_GetFunctionID (183)
/* dss:Device-GetFunctionID */
struct dss__Device_GetFunctionID
{
public:
	int _token;	/* required element of type xsd:int */
	unsigned long _deviceID;	/* required element of type xsd:unsignedInt */
};
#endif

#ifndef SOAP_TYPE_dss__Switch_GetGroupIDResponse
#define SOAP_TYPE_dss__Switch_GetGroupIDResponse (185)
/* dss:Switch-GetGroupIDResponse */
struct dss__Switch_GetGroupIDResponse
{
public:
	int result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Switch_GetGroupID
#define SOAP_TYPE_dss__Switch_GetGroupID (186)
/* dss:Switch-GetGroupID */
struct dss__Switch_GetGroupID
{
public:
	int _token;	/* required element of type xsd:int */
	unsigned long _deviceID;	/* required element of type xsd:unsignedInt */
};
#endif

#ifndef SOAP_TYPE_dss__inParameter
#define SOAP_TYPE_dss__inParameter (187)
/* dss:inParameter */
class SOAP_CMAC dss__inParameter
{
public:
	StringArray *values;	/* optional element of type ArrayOfstring */
	StringArray *names;	/* optional element of type ArrayOfstring */
public:
	virtual int soap_type() const { return 187; } /* = unique id SOAP_TYPE_dss__inParameter */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         dss__inParameter() : values(NULL), names(NULL) { }
	virtual ~dss__inParameter() { }
};
#endif

#ifndef SOAP_TYPE_dss__outParameter
#define SOAP_TYPE_dss__outParameter (189)
/* dss:outParameter */
class SOAP_CMAC dss__outParameter
{
public:
	StringArray *values;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ArrayOfstring */
	StringArray *names;	/* optional element of type ArrayOfstring */
public:
	virtual int soap_type() const { return 189; } /* = unique id SOAP_TYPE_dss__outParameter */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         dss__outParameter() : values(NULL), names(NULL) { }
	virtual ~dss__outParameter() { }
};
#endif

#ifndef SOAP_TYPE_dss__Event_RaiseResponse
#define SOAP_TYPE_dss__Event_RaiseResponse (191)
/* dss:Event-RaiseResponse */
struct dss__Event_RaiseResponse
{
public:
	int result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Event_Raise
#define SOAP_TYPE_dss__Event_Raise (192)
/* dss:Event-Raise */
struct dss__Event_Raise
{
public:
	int _token;	/* required element of type xsd:int */
	int _eventID;	/* required element of type xsd:int */
	int _sourceID;	/* required element of type xsd:int */
	dss__inParameter _params;	/* required element of type dss:inParameter */
};
#endif

#ifndef SOAP_TYPE_dss__Event_GetActionNamesResponse
#define SOAP_TYPE_dss__Event_GetActionNamesResponse (195)
/* dss:Event-GetActionNamesResponse */
struct dss__Event_GetActionNamesResponse
{
public:
	StringArray names;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type ArrayOfstring */
};
#endif

#ifndef SOAP_TYPE_dss__Event_GetActionNames
#define SOAP_TYPE_dss__Event_GetActionNames (196)
/* dss:Event-GetActionNames */
struct dss__Event_GetActionNames
{
public:
	int _token;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Event_GetActionParamsTemplate
#define SOAP_TYPE_dss__Event_GetActionParamsTemplate (199)
/* dss:Event-GetActionParamsTemplate */
struct dss__Event_GetActionParamsTemplate
{
public:
	int _token;	/* required element of type xsd:int */
	char *_name;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_dss__Event_SubscribeResponse
#define SOAP_TYPE_dss__Event_SubscribeResponse (201)
/* dss:Event-SubscribeResponse */
struct dss__Event_SubscribeResponse
{
public:
	int subscriptionID;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Event_Subscribe
#define SOAP_TYPE_dss__Event_Subscribe (202)
/* dss:Event-Subscribe */
struct dss__Event_Subscribe
{
public:
	int _token;	/* required element of type xsd:int */
	IntArray _eventIDs;	/* required element of type ArrayOfunsignedInt */
	IntArray _sourceIDs;	/* required element of type ArrayOfunsignedInt */
	char *_actionName;	/* optional element of type xsd:string */
	dss__inParameter _params;	/* required element of type dss:inParameter */
};
#endif

#ifndef SOAP_TYPE_dss__Event_UnsubscribeResponse
#define SOAP_TYPE_dss__Event_UnsubscribeResponse (204)
/* dss:Event-UnsubscribeResponse */
struct dss__Event_UnsubscribeResponse
{
public:
	int result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Event_Unsubscribe
#define SOAP_TYPE_dss__Event_Unsubscribe (205)
/* dss:Event-Unsubscribe */
struct dss__Event_Unsubscribe
{
public:
	int _token;	/* required element of type xsd:int */
	int _subscriptionID;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Event_ScheduleResponse
#define SOAP_TYPE_dss__Event_ScheduleResponse (207)
/* dss:Event-ScheduleResponse */
struct dss__Event_ScheduleResponse
{
public:
	int scheduledEventID;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Event_Schedule
#define SOAP_TYPE_dss__Event_Schedule (208)
/* dss:Event-Schedule */
struct dss__Event_Schedule
{
public:
	int _token;	/* required element of type xsd:int */
	char *_icalString;	/* optional element of type xsd:string */
	int _eventID;	/* required element of type xsd:int */
	dss__inParameter _params;	/* required element of type dss:inParameter */
};
#endif

#ifndef SOAP_TYPE_dss__Event_DeleteScheduleResponse
#define SOAP_TYPE_dss__Event_DeleteScheduleResponse (210)
/* dss:Event-DeleteScheduleResponse */
struct dss__Event_DeleteScheduleResponse
{
public:
	int result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Event_DeleteSchedule
#define SOAP_TYPE_dss__Event_DeleteSchedule (211)
/* dss:Event-DeleteSchedule */
struct dss__Event_DeleteSchedule
{
public:
	int _token;	/* required element of type xsd:int */
	int _scheduleEventID;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (212)
/* SOAP Header: */
struct SOAP_ENV__Header
{
#ifdef WITH_NOEMPTYSTRUCT
private:
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (213)
/* SOAP Fault Code: */
struct SOAP_ENV__Code
{
public:
	char *SOAP_ENV__Value;	/* optional element of type xsd:QName */
	struct SOAP_ENV__Code *SOAP_ENV__Subcode;	/* optional element of type SOAP-ENV:Code */
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (215)
/* SOAP-ENV:Detail */
struct SOAP_ENV__Detail
{
public:
	int __type;	/* any type of element <fault> (defined below) */
	void *fault;	/* transient */
	char *__any;
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (218)
/* SOAP-ENV:Reason */
struct SOAP_ENV__Reason
{
public:
	char *SOAP_ENV__Text;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (219)
/* SOAP Fault: */
struct SOAP_ENV__Fault
{
public:
	char *faultcode;	/* optional element of type xsd:QName */
	char *faultstring;	/* optional element of type xsd:string */
	char *faultactor;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *detail;	/* optional element of type SOAP-ENV:Detail */
	struct SOAP_ENV__Code *SOAP_ENV__Code;	/* optional element of type SOAP-ENV:Code */
	struct SOAP_ENV__Reason *SOAP_ENV__Reason;	/* optional element of type SOAP-ENV:Reason */
	char *SOAP_ENV__Node;	/* optional element of type xsd:string */
	char *SOAP_ENV__Role;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *SOAP_ENV__Detail;	/* optional element of type SOAP-ENV:Detail */
};
#endif

/******************************************************************************\
 *                                                                            *
 * Types with Custom Serializers                                              *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Typedefs                                                                   *
 *                                                                            *
\******************************************************************************/

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
typedef char *_QName;
#endif

#ifndef SOAP_TYPE__XML
#define SOAP_TYPE__XML (6)
typedef char *_XML;
#endif

#ifndef SOAP_TYPE_xsd__unsignedInt
#define SOAP_TYPE_xsd__unsignedInt (10)
typedef unsigned long xsd__unsignedInt;
#endif


/******************************************************************************\
 *                                                                            *
 * Typedef Synonyms                                                           *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Externals                                                                  *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Service Operations                                                         *
 *                                                                            *
\******************************************************************************/


SOAP_FMAC5 int SOAP_FMAC6 dss__Authenticate(struct soap*, char *_userName, char *_password, int &token);

SOAP_FMAC5 int SOAP_FMAC6 dss__SignOff(struct soap*, int _token, int &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__FreeSet(struct soap*, int _token, int _setID, bool &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__Apartment_CreateSetFromGroup(struct soap*, int _token, char *_groupName, int &setID);

SOAP_FMAC5 int SOAP_FMAC6 dss__Apartment_CreateSetFromDeviceIDs(struct soap*, int _token, IntArray _ids, int &setID);

SOAP_FMAC5 int SOAP_FMAC6 dss__Apartment_CreateSetFromDeviceNames(struct soap*, int _token, StringArray _names, int &setID);

SOAP_FMAC5 int SOAP_FMAC6 dss__Apartment_CreateEmptySet(struct soap*, int _token, int &setID);

SOAP_FMAC5 int SOAP_FMAC6 dss__Apartment_GetDevices(struct soap*, int _token, int &setID);

SOAP_FMAC5 int SOAP_FMAC6 dss__Apartment_GetDeviceIDByName(struct soap*, int _token, char *_deviceName, int &deviceID);

SOAP_FMAC5 int SOAP_FMAC6 dss__Set_AddDeviceByName(struct soap*, int _token, int _setID, char *_name, bool &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__Set_AddDeviceByID(struct soap*, int _token, int _setID, int _deviceID, bool &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__Set_RemoveDevice(struct soap*, int _token, int _setID, int _deviceID, bool &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__Set_Combine(struct soap*, int _token, int _setID1, int _setID2, int &setID);

SOAP_FMAC5 int SOAP_FMAC6 dss__Set_Remove(struct soap*, int _token, int _setID, int _setIDToRemove, int &setID);

SOAP_FMAC5 int SOAP_FMAC6 dss__Set_ByGroup(struct soap*, int _token, int _setID, int _groupID, int &setID);

SOAP_FMAC5 int SOAP_FMAC6 dss__Set_GetContainedDevices(struct soap*, int _token, int _setID, IntArray &deviceIDs);

SOAP_FMAC5 int SOAP_FMAC6 dss__Apartment_GetGroupByName(struct soap*, int _token, char *_groupName, int &groupID);

SOAP_FMAC5 int SOAP_FMAC6 dss__Apartment_GetRoomByName(struct soap*, int _token, char *_roomName, int &roomID);

SOAP_FMAC5 int SOAP_FMAC6 dss__Apartment_GetRoomIDs(struct soap*, int _token, IntArray &roomIDs);

SOAP_FMAC5 int SOAP_FMAC6 dss__Set_TurnOn(struct soap*, int _token, int _setID, bool &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__Set_TurnOff(struct soap*, int _token, int _setID, bool &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__Set_IncreaseValue(struct soap*, int _token, int _setID, int _paramID, bool &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__Set_DecreaseValue(struct soap*, int _token, int _setID, int _paramID, bool &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__Set_Enable(struct soap*, int _token, int _setID, bool &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__Set_Disable(struct soap*, int _token, int _setID, bool &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__Set_StartDim(struct soap*, int _token, int _setID, bool _directionUp, int _paramID, bool &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__Set_EndDim(struct soap*, int _token, int _setID, int _paramID, bool &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__Set_SetValue(struct soap*, int _token, int _setID, double _value, int _paramID, bool &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__Device_TurnOn(struct soap*, int _token, unsigned long _deviceID, bool &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__Device_TurnOff(struct soap*, int _token, unsigned long _deviceID, bool &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__Device_IncreaseValue(struct soap*, int _token, unsigned long _deviceID, int _paramID, bool &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__Device_DecreaseValue(struct soap*, int _token, unsigned long _deviceID, int _paramID, bool &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__Device_Enable(struct soap*, int _token, unsigned long _deviceID, bool &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__Device_Disable(struct soap*, int _token, unsigned long _deviceID, bool &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__Device_StartDim(struct soap*, int _token, unsigned long _deviceID, bool _directionUp, int _paramID, bool &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__Device_EndDim(struct soap*, int _token, unsigned long _deviceID, int _paramID, bool &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__Device_SetValue(struct soap*, int _token, unsigned long _deviceID, double _value, int _paramID, bool &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__Device_GetValue(struct soap*, int _token, unsigned long _deviceID, int _paramID, double &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__Device_GetName(struct soap*, int _token, unsigned long _deviceID, char **result);

SOAP_FMAC5 int SOAP_FMAC6 dss__Device_GetRoomID(struct soap*, int _token, unsigned long _deviceID, int &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__Device_GetDSID(struct soap*, int _token, unsigned long _deviceID, unsigned long &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__Apartment_GetModulatorIDs(struct soap*, int _token, IntArray &ids);

SOAP_FMAC5 int SOAP_FMAC6 dss__Modulator_GetDSID(struct soap*, int _token, int _modulatorID, unsigned long &dsid);

SOAP_FMAC5 int SOAP_FMAC6 dss__Modulator_GetName(struct soap*, int _token, int _modulatorID, char **name);

SOAP_FMAC5 int SOAP_FMAC6 dss__Apartment_AllocateRoom(struct soap*, int _token, int &roomID);

SOAP_FMAC5 int SOAP_FMAC6 dss__Apartment_DeleteRoom(struct soap*, int _token, int _roomID, int &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__Room_AddDevice(struct soap*, int _token, int _roomID, int _deviceID, int &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__Room_RemoveDevice(struct soap*, int _token, int _roomID, int _deviceID, int &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__Room_SetName(struct soap*, int _token, int _roomID, char *_name, int &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__Apartment_AllocateUserGroup(struct soap*, int _token, int &groupID);

SOAP_FMAC5 int SOAP_FMAC6 dss__Group_RemoveUserGroup(struct soap*, int _token, int _groupID, int &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__Group_AddDevice(struct soap*, int _token, int _groupID, int _deviceID, int &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__Group_RemoveDevice(struct soap*, int _token, int _groupID, int _deviceID, int &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__Device_GetFunctionID(struct soap*, int _token, unsigned long _deviceID, int &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__Switch_GetGroupID(struct soap*, int _token, unsigned long _deviceID, int &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__Event_Raise(struct soap*, int _token, int _eventID, int _sourceID, dss__inParameter _params, int &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__Event_GetActionNames(struct soap*, int _token, StringArray &names);

SOAP_FMAC5 int SOAP_FMAC6 dss__Event_GetActionParamsTemplate(struct soap*, int _token, char *_name, dss__outParameter &paramsTemplate);

SOAP_FMAC5 int SOAP_FMAC6 dss__Event_Subscribe(struct soap*, int _token, IntArray _eventIDs, IntArray _sourceIDs, char *_actionName, dss__inParameter _params, int &subscriptionID);

SOAP_FMAC5 int SOAP_FMAC6 dss__Event_Unsubscribe(struct soap*, int _token, int _subscriptionID, int &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__Event_Schedule(struct soap*, int _token, char *_icalString, int _eventID, dss__inParameter _params, int &scheduledEventID);

SOAP_FMAC5 int SOAP_FMAC6 dss__Event_DeleteSchedule(struct soap*, int _token, int _scheduleEventID, int &result);

/******************************************************************************\
 *                                                                            *
 * Skeletons                                                                  *
 *                                                                            *
\******************************************************************************/

SOAP_FMAC5 int SOAP_FMAC6 soap_serve(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_request(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__Authenticate(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__SignOff(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__FreeSet(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__Apartment_CreateSetFromGroup(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__Apartment_CreateSetFromDeviceIDs(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__Apartment_CreateSetFromDeviceNames(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__Apartment_CreateEmptySet(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__Apartment_GetDevices(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__Apartment_GetDeviceIDByName(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__Set_AddDeviceByName(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__Set_AddDeviceByID(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__Set_RemoveDevice(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__Set_Combine(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__Set_Remove(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__Set_ByGroup(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__Set_GetContainedDevices(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__Apartment_GetGroupByName(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__Apartment_GetRoomByName(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__Apartment_GetRoomIDs(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__Set_TurnOn(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__Set_TurnOff(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__Set_IncreaseValue(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__Set_DecreaseValue(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__Set_Enable(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__Set_Disable(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__Set_StartDim(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__Set_EndDim(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__Set_SetValue(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__Device_TurnOn(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__Device_TurnOff(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__Device_IncreaseValue(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__Device_DecreaseValue(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__Device_Enable(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__Device_Disable(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__Device_StartDim(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__Device_EndDim(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__Device_SetValue(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__Device_GetValue(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__Device_GetName(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__Device_GetRoomID(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__Device_GetDSID(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__Apartment_GetModulatorIDs(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__Modulator_GetDSID(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__Modulator_GetName(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__Apartment_AllocateRoom(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__Apartment_DeleteRoom(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__Room_AddDevice(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__Room_RemoveDevice(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__Room_SetName(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__Apartment_AllocateUserGroup(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__Group_RemoveUserGroup(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__Group_AddDevice(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__Group_RemoveDevice(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__Device_GetFunctionID(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__Switch_GetGroupID(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__Event_Raise(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__Event_GetActionNames(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__Event_GetActionParamsTemplate(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__Event_Subscribe(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__Event_Unsubscribe(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__Event_Schedule(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__Event_DeleteSchedule(struct soap*);

#endif

/* End of soapStub.h */
