/* soapStub.h
   Generated by gSOAP 2.7.10 from model_soap.h
   Copyright(C) 2000-2008, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef soapStub_H
#define soapStub_H
#include "stdsoap2.h"

/******************************************************************************\
 *                                                                            *
 * Enumerations                                                               *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Classes and Structs                                                        *
 *                                                                            *
\******************************************************************************/


#if 0 /* volatile type: do not redeclare here */

#endif

#ifndef SOAP_TYPE_IntArray
#define SOAP_TYPE_IntArray (7)
/* SOAP encoded array of xsd:int schema type: */
class SOAP_CMAC IntArray
{
public:
	int *__ptr;
	int __size;
public:
	virtual int soap_type() const { return 7; } /* = unique id SOAP_TYPE_IntArray */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         IntArray() : __ptr(NULL), __size(0) { }
	virtual ~IntArray() { }
};
#endif

#ifndef SOAP_TYPE_StringArray
#define SOAP_TYPE_StringArray (9)
/* SOAP encoded array of xsd:string schema type: */
class SOAP_CMAC StringArray
{
public:
	char **__ptr;
	int __size;
public:
	virtual int soap_type() const { return 9; } /* = unique id SOAP_TYPE_StringArray */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         StringArray() : __ptr(NULL), __size(0) { }
	virtual ~StringArray() { }
};
#endif

#ifndef SOAP_TYPE_dss__AuthenticateResponse
#define SOAP_TYPE_dss__AuthenticateResponse (16)
/* dss:AuthenticateResponse */
struct dss__AuthenticateResponse
{
public:
	int token;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Authenticate
#define SOAP_TYPE_dss__Authenticate (17)
/* dss:Authenticate */
struct dss__Authenticate
{
public:
	char *_userName;	/* optional element of type xsd:string */
	char *_password;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_dss__SignOffResponse
#define SOAP_TYPE_dss__SignOffResponse (19)
/* dss:SignOffResponse */
struct dss__SignOffResponse
{
public:
	int result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__SignOff
#define SOAP_TYPE_dss__SignOff (20)
/* dss:SignOff */
struct dss__SignOff
{
public:
	int _token;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Apartment_CreateSetFromGroupResponse
#define SOAP_TYPE_dss__Apartment_CreateSetFromGroupResponse (22)
/* dss:Apartment-CreateSetFromGroupResponse */
struct dss__Apartment_CreateSetFromGroupResponse
{
public:
	int setID;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Apartment_CreateSetFromGroup
#define SOAP_TYPE_dss__Apartment_CreateSetFromGroup (23)
/* dss:Apartment-CreateSetFromGroup */
struct dss__Apartment_CreateSetFromGroup
{
public:
	int _token;	/* required element of type xsd:int */
	char *_groupName;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_dss__Apartment_CreateSetFromDeviceIDsResponse
#define SOAP_TYPE_dss__Apartment_CreateSetFromDeviceIDsResponse (25)
/* dss:Apartment-CreateSetFromDeviceIDsResponse */
struct dss__Apartment_CreateSetFromDeviceIDsResponse
{
public:
	int setID;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Apartment_CreateSetFromDeviceIDs
#define SOAP_TYPE_dss__Apartment_CreateSetFromDeviceIDs (26)
/* dss:Apartment-CreateSetFromDeviceIDs */
struct dss__Apartment_CreateSetFromDeviceIDs
{
public:
	int _token;	/* required element of type xsd:int */
	IntArray _ids;	/* required element of type ArrayOfint */
};
#endif

#ifndef SOAP_TYPE_dss__Apartment_CreateSetFromDeviceNamesResponse
#define SOAP_TYPE_dss__Apartment_CreateSetFromDeviceNamesResponse (28)
/* dss:Apartment-CreateSetFromDeviceNamesResponse */
struct dss__Apartment_CreateSetFromDeviceNamesResponse
{
public:
	int setID;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Apartment_CreateSetFromDeviceNames
#define SOAP_TYPE_dss__Apartment_CreateSetFromDeviceNames (29)
/* dss:Apartment-CreateSetFromDeviceNames */
struct dss__Apartment_CreateSetFromDeviceNames
{
public:
	int _token;	/* required element of type xsd:int */
	StringArray _names;	/* required element of type ArrayOfstring */
};
#endif

#ifndef SOAP_TYPE_dss__Apartment_CreateEmptySetResponse
#define SOAP_TYPE_dss__Apartment_CreateEmptySetResponse (31)
/* dss:Apartment-CreateEmptySetResponse */
struct dss__Apartment_CreateEmptySetResponse
{
public:
	int setID;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Apartment_CreateEmptySet
#define SOAP_TYPE_dss__Apartment_CreateEmptySet (32)
/* dss:Apartment-CreateEmptySet */
struct dss__Apartment_CreateEmptySet
{
public:
	int _token;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Apartment_GetDevicesResponse
#define SOAP_TYPE_dss__Apartment_GetDevicesResponse (34)
/* dss:Apartment-GetDevicesResponse */
struct dss__Apartment_GetDevicesResponse
{
public:
	int setID;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Apartment_GetDevices
#define SOAP_TYPE_dss__Apartment_GetDevices (35)
/* dss:Apartment-GetDevices */
struct dss__Apartment_GetDevices
{
public:
	int _token;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Apartment_GetDeviceIDByNameResponse
#define SOAP_TYPE_dss__Apartment_GetDeviceIDByNameResponse (37)
/* dss:Apartment-GetDeviceIDByNameResponse */
struct dss__Apartment_GetDeviceIDByNameResponse
{
public:
	int deviceID;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Apartment_GetDeviceIDByName
#define SOAP_TYPE_dss__Apartment_GetDeviceIDByName (38)
/* dss:Apartment-GetDeviceIDByName */
struct dss__Apartment_GetDeviceIDByName
{
public:
	int _token;	/* required element of type xsd:int */
	char *_deviceName;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_dss__Set_AddDeviceByNameResponse
#define SOAP_TYPE_dss__Set_AddDeviceByNameResponse (42)
/* dss:Set-AddDeviceByNameResponse */
struct dss__Set_AddDeviceByNameResponse
{
public:
	bool result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:boolean */
};
#endif

#ifndef SOAP_TYPE_dss__Set_AddDeviceByName
#define SOAP_TYPE_dss__Set_AddDeviceByName (43)
/* dss:Set-AddDeviceByName */
struct dss__Set_AddDeviceByName
{
public:
	int _token;	/* required element of type xsd:int */
	int _setID;	/* required element of type xsd:int */
	char *_name;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_dss__Set_AddDeviceByIDResponse
#define SOAP_TYPE_dss__Set_AddDeviceByIDResponse (45)
/* dss:Set-AddDeviceByIDResponse */
struct dss__Set_AddDeviceByIDResponse
{
public:
	bool result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:boolean */
};
#endif

#ifndef SOAP_TYPE_dss__Set_AddDeviceByID
#define SOAP_TYPE_dss__Set_AddDeviceByID (46)
/* dss:Set-AddDeviceByID */
struct dss__Set_AddDeviceByID
{
public:
	int _token;	/* required element of type xsd:int */
	int _setID;	/* required element of type xsd:int */
	int _deviceID;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Set_RemoveDeviceResponse
#define SOAP_TYPE_dss__Set_RemoveDeviceResponse (48)
/* dss:Set-RemoveDeviceResponse */
struct dss__Set_RemoveDeviceResponse
{
public:
	bool result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:boolean */
};
#endif

#ifndef SOAP_TYPE_dss__Set_RemoveDevice
#define SOAP_TYPE_dss__Set_RemoveDevice (49)
/* dss:Set-RemoveDevice */
struct dss__Set_RemoveDevice
{
public:
	int _token;	/* required element of type xsd:int */
	int _setID;	/* required element of type xsd:int */
	int _deviceID;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Set_CombineResponse
#define SOAP_TYPE_dss__Set_CombineResponse (51)
/* dss:Set-CombineResponse */
struct dss__Set_CombineResponse
{
public:
	int setID;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Set_Combine
#define SOAP_TYPE_dss__Set_Combine (52)
/* dss:Set-Combine */
struct dss__Set_Combine
{
public:
	int _token;	/* required element of type xsd:int */
	int _setID1;	/* required element of type xsd:int */
	int _setID2;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Set_RemoveResponse
#define SOAP_TYPE_dss__Set_RemoveResponse (54)
/* dss:Set-RemoveResponse */
struct dss__Set_RemoveResponse
{
public:
	int setID;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Set_Remove
#define SOAP_TYPE_dss__Set_Remove (55)
/* dss:Set-Remove */
struct dss__Set_Remove
{
public:
	int _token;	/* required element of type xsd:int */
	int _setID;	/* required element of type xsd:int */
	int _setIDToRemove;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Set_ByGroupResponse
#define SOAP_TYPE_dss__Set_ByGroupResponse (57)
/* dss:Set-ByGroupResponse */
struct dss__Set_ByGroupResponse
{
public:
	int setID;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Set_ByGroup
#define SOAP_TYPE_dss__Set_ByGroup (58)
/* dss:Set-ByGroup */
struct dss__Set_ByGroup
{
public:
	int _token;	/* required element of type xsd:int */
	int _setID;	/* required element of type xsd:int */
	int _groupID;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Apartment_GetGroupByNameResponse
#define SOAP_TYPE_dss__Apartment_GetGroupByNameResponse (60)
/* dss:Apartment-GetGroupByNameResponse */
struct dss__Apartment_GetGroupByNameResponse
{
public:
	int groupID;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Apartment_GetGroupByName
#define SOAP_TYPE_dss__Apartment_GetGroupByName (61)
/* dss:Apartment-GetGroupByName */
struct dss__Apartment_GetGroupByName
{
public:
	int _token;	/* required element of type xsd:int */
	int _groupName;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Apartment_GetRoomByNameResponse
#define SOAP_TYPE_dss__Apartment_GetRoomByNameResponse (63)
/* dss:Apartment-GetRoomByNameResponse */
struct dss__Apartment_GetRoomByNameResponse
{
public:
	int roomID;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Apartment_GetRoomByName
#define SOAP_TYPE_dss__Apartment_GetRoomByName (64)
/* dss:Apartment-GetRoomByName */
struct dss__Apartment_GetRoomByName
{
public:
	int _token;	/* required element of type xsd:int */
	char *_roomName;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_dss__Apartment_GetRoomIDsResponse
#define SOAP_TYPE_dss__Apartment_GetRoomIDsResponse (67)
/* dss:Apartment-GetRoomIDsResponse */
struct dss__Apartment_GetRoomIDsResponse
{
public:
	IntArray roomIDs;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type ArrayOfint */
};
#endif

#ifndef SOAP_TYPE_dss__Apartment_GetRoomIDs
#define SOAP_TYPE_dss__Apartment_GetRoomIDs (68)
/* dss:Apartment-GetRoomIDs */
struct dss__Apartment_GetRoomIDs
{
public:
	int _token;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Set_TurnOnResponse
#define SOAP_TYPE_dss__Set_TurnOnResponse (70)
/* dss:Set-TurnOnResponse */
struct dss__Set_TurnOnResponse
{
public:
	int result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Set_TurnOn
#define SOAP_TYPE_dss__Set_TurnOn (71)
/* dss:Set-TurnOn */
struct dss__Set_TurnOn
{
public:
	int _token;	/* required element of type xsd:int */
	int _setID;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Set_TurnOffResponse
#define SOAP_TYPE_dss__Set_TurnOffResponse (73)
/* dss:Set-TurnOffResponse */
struct dss__Set_TurnOffResponse
{
public:
	int result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Set_TurnOff
#define SOAP_TYPE_dss__Set_TurnOff (74)
/* dss:Set-TurnOff */
struct dss__Set_TurnOff
{
public:
	int _token;	/* required element of type xsd:int */
	int _setID;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Set_IncreaseValueResponse
#define SOAP_TYPE_dss__Set_IncreaseValueResponse (76)
/* dss:Set-IncreaseValueResponse */
struct dss__Set_IncreaseValueResponse
{
public:
	int result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Set_IncreaseValue
#define SOAP_TYPE_dss__Set_IncreaseValue (77)
/* dss:Set-IncreaseValue */
struct dss__Set_IncreaseValue
{
public:
	int _token;	/* required element of type xsd:int */
	int _setID;	/* required element of type xsd:int */
	int _paramID;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Set_DecreaseValueResponse
#define SOAP_TYPE_dss__Set_DecreaseValueResponse (79)
/* dss:Set-DecreaseValueResponse */
struct dss__Set_DecreaseValueResponse
{
public:
	int result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Set_DecreaseValue
#define SOAP_TYPE_dss__Set_DecreaseValue (80)
/* dss:Set-DecreaseValue */
struct dss__Set_DecreaseValue
{
public:
	int _token;	/* required element of type xsd:int */
	int _setID;	/* required element of type xsd:int */
	int _paramID;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Set_EnableResponse
#define SOAP_TYPE_dss__Set_EnableResponse (82)
/* dss:Set-EnableResponse */
struct dss__Set_EnableResponse
{
public:
	int result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Set_Enable
#define SOAP_TYPE_dss__Set_Enable (83)
/* dss:Set-Enable */
struct dss__Set_Enable
{
public:
	int _token;	/* required element of type xsd:int */
	int _setID;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Set_DisableResponse
#define SOAP_TYPE_dss__Set_DisableResponse (85)
/* dss:Set-DisableResponse */
struct dss__Set_DisableResponse
{
public:
	int result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Set_Disable
#define SOAP_TYPE_dss__Set_Disable (86)
/* dss:Set-Disable */
struct dss__Set_Disable
{
public:
	int _token;	/* required element of type xsd:int */
	int _setID;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Set_StartDimResponse
#define SOAP_TYPE_dss__Set_StartDimResponse (88)
/* dss:Set-StartDimResponse */
struct dss__Set_StartDimResponse
{
public:
	int result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Set_StartDim
#define SOAP_TYPE_dss__Set_StartDim (89)
/* dss:Set-StartDim */
struct dss__Set_StartDim
{
public:
	int _token;	/* required element of type xsd:int */
	int _setID;	/* required element of type xsd:int */
	bool _directionUp;	/* required element of type xsd:boolean */
	int _paramID;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Set_EndDimResponse
#define SOAP_TYPE_dss__Set_EndDimResponse (91)
/* dss:Set-EndDimResponse */
struct dss__Set_EndDimResponse
{
public:
	int result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Set_EndDim
#define SOAP_TYPE_dss__Set_EndDim (92)
/* dss:Set-EndDim */
struct dss__Set_EndDim
{
public:
	int _token;	/* required element of type xsd:int */
	int _setID;	/* required element of type xsd:int */
	int _paramID;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Set_SetValueResponse
#define SOAP_TYPE_dss__Set_SetValueResponse (95)
/* dss:Set-SetValueResponse */
struct dss__Set_SetValueResponse
{
public:
	int result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Set_SetValue
#define SOAP_TYPE_dss__Set_SetValue (96)
/* dss:Set-SetValue */
struct dss__Set_SetValue
{
public:
	int _token;	/* required element of type xsd:int */
	int _setID;	/* required element of type xsd:int */
	float _value;	/* required element of type xsd:float */
	int _paramID;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Device_TurnOnResponse
#define SOAP_TYPE_dss__Device_TurnOnResponse (98)
/* dss:Device-TurnOnResponse */
struct dss__Device_TurnOnResponse
{
public:
	int result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Device_TurnOn
#define SOAP_TYPE_dss__Device_TurnOn (99)
/* dss:Device-TurnOn */
struct dss__Device_TurnOn
{
public:
	int _token;	/* required element of type xsd:int */
	int _deviceID;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Device_TurnOffResponse
#define SOAP_TYPE_dss__Device_TurnOffResponse (101)
/* dss:Device-TurnOffResponse */
struct dss__Device_TurnOffResponse
{
public:
	int result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Device_TurnOff
#define SOAP_TYPE_dss__Device_TurnOff (102)
/* dss:Device-TurnOff */
struct dss__Device_TurnOff
{
public:
	int _token;	/* required element of type xsd:int */
	int _deviceID;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Device_IncreaseValueResponse
#define SOAP_TYPE_dss__Device_IncreaseValueResponse (104)
/* dss:Device-IncreaseValueResponse */
struct dss__Device_IncreaseValueResponse
{
public:
	int result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Device_IncreaseValue
#define SOAP_TYPE_dss__Device_IncreaseValue (105)
/* dss:Device-IncreaseValue */
struct dss__Device_IncreaseValue
{
public:
	int _token;	/* required element of type xsd:int */
	int _deviceID;	/* required element of type xsd:int */
	int _paramID;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Device_DecreaseValueResponse
#define SOAP_TYPE_dss__Device_DecreaseValueResponse (107)
/* dss:Device-DecreaseValueResponse */
struct dss__Device_DecreaseValueResponse
{
public:
	int result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Device_DecreaseValue
#define SOAP_TYPE_dss__Device_DecreaseValue (108)
/* dss:Device-DecreaseValue */
struct dss__Device_DecreaseValue
{
public:
	int _token;	/* required element of type xsd:int */
	int _deviceID;	/* required element of type xsd:int */
	int _paramID;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Device_EnableResponse
#define SOAP_TYPE_dss__Device_EnableResponse (110)
/* dss:Device-EnableResponse */
struct dss__Device_EnableResponse
{
public:
	int result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Device_Enable
#define SOAP_TYPE_dss__Device_Enable (111)
/* dss:Device-Enable */
struct dss__Device_Enable
{
public:
	int _token;	/* required element of type xsd:int */
	int _deviceID;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Device_DisableResponse
#define SOAP_TYPE_dss__Device_DisableResponse (113)
/* dss:Device-DisableResponse */
struct dss__Device_DisableResponse
{
public:
	int result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Device_Disable
#define SOAP_TYPE_dss__Device_Disable (114)
/* dss:Device-Disable */
struct dss__Device_Disable
{
public:
	int _token;	/* required element of type xsd:int */
	int _deviceID;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Device_StartDimResponse
#define SOAP_TYPE_dss__Device_StartDimResponse (116)
/* dss:Device-StartDimResponse */
struct dss__Device_StartDimResponse
{
public:
	int result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Device_StartDim
#define SOAP_TYPE_dss__Device_StartDim (117)
/* dss:Device-StartDim */
struct dss__Device_StartDim
{
public:
	int _token;	/* required element of type xsd:int */
	int _deviceID;	/* required element of type xsd:int */
	bool _directionUp;	/* required element of type xsd:boolean */
	int _paramID;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Device_EndDimResponse
#define SOAP_TYPE_dss__Device_EndDimResponse (119)
/* dss:Device-EndDimResponse */
struct dss__Device_EndDimResponse
{
public:
	int result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Device_EndDim
#define SOAP_TYPE_dss__Device_EndDim (120)
/* dss:Device-EndDim */
struct dss__Device_EndDim
{
public:
	int _token;	/* required element of type xsd:int */
	int _deviceID;	/* required element of type xsd:int */
	int _paramID;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Device_SetValueResponse
#define SOAP_TYPE_dss__Device_SetValueResponse (122)
/* dss:Device-SetValueResponse */
struct dss__Device_SetValueResponse
{
public:
	int result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Device_SetValue
#define SOAP_TYPE_dss__Device_SetValue (123)
/* dss:Device-SetValue */
struct dss__Device_SetValue
{
public:
	int _token;	/* required element of type xsd:int */
	int _deviceID;	/* required element of type xsd:int */
	float _value;	/* required element of type xsd:float */
	int _paramID;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Device_GetValueResponse
#define SOAP_TYPE_dss__Device_GetValueResponse (126)
/* dss:Device-GetValueResponse */
struct dss__Device_GetValueResponse
{
public:
	float result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:float */
};
#endif

#ifndef SOAP_TYPE_dss__Device_GetValue
#define SOAP_TYPE_dss__Device_GetValue (127)
/* dss:Device-GetValue */
struct dss__Device_GetValue
{
public:
	int _token;	/* required element of type xsd:int */
	int _deviceID;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Device_GetDSIDResponse
#define SOAP_TYPE_dss__Device_GetDSIDResponse (130)
/* dss:Device-GetDSIDResponse */
struct dss__Device_GetDSIDResponse
{
public:
	LONG64 result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type DSID */
};
#endif

#ifndef SOAP_TYPE_dss__Device_GetDSID
#define SOAP_TYPE_dss__Device_GetDSID (131)
/* dss:Device-GetDSID */
struct dss__Device_GetDSID
{
public:
	int _token;	/* required element of type xsd:int */
	int _deviceID;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Apartment_GetModulatorIDsResponse
#define SOAP_TYPE_dss__Apartment_GetModulatorIDsResponse (133)
/* dss:Apartment-GetModulatorIDsResponse */
struct dss__Apartment_GetModulatorIDsResponse
{
public:
	IntArray ids;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type ArrayOfint */
};
#endif

#ifndef SOAP_TYPE_dss__Apartment_GetModulatorIDs
#define SOAP_TYPE_dss__Apartment_GetModulatorIDs (134)
/* dss:Apartment-GetModulatorIDs */
struct dss__Apartment_GetModulatorIDs
{
public:
	int _token;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Modulator_GetDSIDResponse
#define SOAP_TYPE_dss__Modulator_GetDSIDResponse (136)
/* dss:Modulator-GetDSIDResponse */
struct dss__Modulator_GetDSIDResponse
{
public:
	LONG64 dsid;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type DSID */
};
#endif

#ifndef SOAP_TYPE_dss__Modulator_GetDSID
#define SOAP_TYPE_dss__Modulator_GetDSID (137)
/* dss:Modulator-GetDSID */
struct dss__Modulator_GetDSID
{
public:
	int _token;	/* required element of type xsd:int */
	int _modulatorID;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Modulator_GetNameResponse
#define SOAP_TYPE_dss__Modulator_GetNameResponse (139)
/* dss:Modulator-GetNameResponse */
struct dss__Modulator_GetNameResponse
{
public:
	char **name;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_dss__Modulator_GetName
#define SOAP_TYPE_dss__Modulator_GetName (140)
/* dss:Modulator-GetName */
struct dss__Modulator_GetName
{
public:
	int _token;	/* required element of type xsd:int */
	int _modulatorID;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Apartment_AllocateRoomResponse
#define SOAP_TYPE_dss__Apartment_AllocateRoomResponse (142)
/* dss:Apartment-AllocateRoomResponse */
struct dss__Apartment_AllocateRoomResponse
{
public:
	int roomID;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Apartment_AllocateRoom
#define SOAP_TYPE_dss__Apartment_AllocateRoom (143)
/* dss:Apartment-AllocateRoom */
struct dss__Apartment_AllocateRoom
{
public:
	int _token;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Apartment_DeleteRoomResponse
#define SOAP_TYPE_dss__Apartment_DeleteRoomResponse (145)
/* dss:Apartment-DeleteRoomResponse */
struct dss__Apartment_DeleteRoomResponse
{
public:
	int result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Apartment_DeleteRoom
#define SOAP_TYPE_dss__Apartment_DeleteRoom (146)
/* dss:Apartment-DeleteRoom */
struct dss__Apartment_DeleteRoom
{
public:
	int _token;	/* required element of type xsd:int */
	int _roomID;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Room_AddDeviceResponse
#define SOAP_TYPE_dss__Room_AddDeviceResponse (148)
/* dss:Room-AddDeviceResponse */
struct dss__Room_AddDeviceResponse
{
public:
	int result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Room_AddDevice
#define SOAP_TYPE_dss__Room_AddDevice (149)
/* dss:Room-AddDevice */
struct dss__Room_AddDevice
{
public:
	int _token;	/* required element of type xsd:int */
	int _roomID;	/* required element of type xsd:int */
	int _deviceID;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Room_RemoveDeviceResponse
#define SOAP_TYPE_dss__Room_RemoveDeviceResponse (151)
/* dss:Room-RemoveDeviceResponse */
struct dss__Room_RemoveDeviceResponse
{
public:
	int result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Room_RemoveDevice
#define SOAP_TYPE_dss__Room_RemoveDevice (152)
/* dss:Room-RemoveDevice */
struct dss__Room_RemoveDevice
{
public:
	int _token;	/* required element of type xsd:int */
	int _roomID;	/* required element of type xsd:int */
	int _deviceID;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Room_SetNameResponse
#define SOAP_TYPE_dss__Room_SetNameResponse (154)
/* dss:Room-SetNameResponse */
struct dss__Room_SetNameResponse
{
public:
	int result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Room_SetName
#define SOAP_TYPE_dss__Room_SetName (155)
/* dss:Room-SetName */
struct dss__Room_SetName
{
public:
	int _token;	/* required element of type xsd:int */
	int _roomID;	/* required element of type xsd:int */
	char *_name;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_dss__Apartment_AllocateUserGroupResponse
#define SOAP_TYPE_dss__Apartment_AllocateUserGroupResponse (157)
/* dss:Apartment-AllocateUserGroupResponse */
struct dss__Apartment_AllocateUserGroupResponse
{
public:
	int groupID;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Apartment_AllocateUserGroup
#define SOAP_TYPE_dss__Apartment_AllocateUserGroup (158)
/* dss:Apartment-AllocateUserGroup */
struct dss__Apartment_AllocateUserGroup
{
public:
	int _token;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Group_RemoveUserGroupResponse
#define SOAP_TYPE_dss__Group_RemoveUserGroupResponse (160)
/* dss:Group-RemoveUserGroupResponse */
struct dss__Group_RemoveUserGroupResponse
{
public:
	int result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Group_RemoveUserGroup
#define SOAP_TYPE_dss__Group_RemoveUserGroup (161)
/* dss:Group-RemoveUserGroup */
struct dss__Group_RemoveUserGroup
{
public:
	int _token;	/* required element of type xsd:int */
	int _groupID;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Group_AddDeviceResponse
#define SOAP_TYPE_dss__Group_AddDeviceResponse (163)
/* dss:Group-AddDeviceResponse */
struct dss__Group_AddDeviceResponse
{
public:
	int result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Group_AddDevice
#define SOAP_TYPE_dss__Group_AddDevice (164)
/* dss:Group-AddDevice */
struct dss__Group_AddDevice
{
public:
	int _token;	/* required element of type xsd:int */
	int _groupID;	/* required element of type xsd:int */
	int _deviceID;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Group_RemoveDeviceResponse
#define SOAP_TYPE_dss__Group_RemoveDeviceResponse (166)
/* dss:Group-RemoveDeviceResponse */
struct dss__Group_RemoveDeviceResponse
{
public:
	int result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Group_RemoveDevice
#define SOAP_TYPE_dss__Group_RemoveDevice (167)
/* dss:Group-RemoveDevice */
struct dss__Group_RemoveDevice
{
public:
	int _token;	/* required element of type xsd:int */
	int _groupID;	/* required element of type xsd:int */
	int _deviceID;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_Parameter
#define SOAP_TYPE_Parameter (168)
/* Parameter */
class SOAP_CMAC Parameter
{
public:
	StringArray *values;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ArrayOfstring */
	StringArray *names;	/* optional element of type ArrayOfstring */
public:
	virtual int soap_type() const { return 168; } /* = unique id SOAP_TYPE_Parameter */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         Parameter() : values(NULL), names(NULL) { }
	virtual ~Parameter() { }
};
#endif

#ifndef SOAP_TYPE_dss__Event_RaiseResponse
#define SOAP_TYPE_dss__Event_RaiseResponse (171)
/* dss:Event-RaiseResponse */
struct dss__Event_RaiseResponse
{
public:
	int result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Event_Raise
#define SOAP_TYPE_dss__Event_Raise (172)
/* dss:Event-Raise */
struct dss__Event_Raise
{
public:
	int _token;	/* required element of type xsd:int */
	int _eventID;	/* required element of type xsd:int */
	int _sourceID;	/* required element of type xsd:int */
	Parameter _params;	/* required element of type Parameter */
};
#endif

#ifndef SOAP_TYPE_dss__Event_GetActionNamesResponse
#define SOAP_TYPE_dss__Event_GetActionNamesResponse (175)
/* dss:Event-GetActionNamesResponse */
struct dss__Event_GetActionNamesResponse
{
public:
	StringArray names;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type ArrayOfstring */
};
#endif

#ifndef SOAP_TYPE_dss__Event_GetActionNames
#define SOAP_TYPE_dss__Event_GetActionNames (176)
/* dss:Event-GetActionNames */
struct dss__Event_GetActionNames
{
public:
	int _token;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Event_GetActionParamsTemplate
#define SOAP_TYPE_dss__Event_GetActionParamsTemplate (179)
/* dss:Event-GetActionParamsTemplate */
struct dss__Event_GetActionParamsTemplate
{
public:
	int _token;	/* required element of type xsd:int */
	char *_name;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_dss__Event_SubscribeResponse
#define SOAP_TYPE_dss__Event_SubscribeResponse (181)
/* dss:Event-SubscribeResponse */
struct dss__Event_SubscribeResponse
{
public:
	int subscriptionID;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Event_Subscribe
#define SOAP_TYPE_dss__Event_Subscribe (182)
/* dss:Event-Subscribe */
struct dss__Event_Subscribe
{
public:
	int _token;	/* required element of type xsd:int */
	IntArray _eventIDs;	/* required element of type ArrayOfint */
	IntArray _sourceIDs;	/* required element of type ArrayOfint */
	char *_actionName;	/* optional element of type xsd:string */
	Parameter _params;	/* required element of type Parameter */
};
#endif

#ifndef SOAP_TYPE_dss__Event_UnsubscribeResponse
#define SOAP_TYPE_dss__Event_UnsubscribeResponse (184)
/* dss:Event-UnsubscribeResponse */
struct dss__Event_UnsubscribeResponse
{
public:
	int result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Event_Unsubscribe
#define SOAP_TYPE_dss__Event_Unsubscribe (185)
/* dss:Event-Unsubscribe */
struct dss__Event_Unsubscribe
{
public:
	int _token;	/* required element of type xsd:int */
	int _subscriptionID;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Event_ScheduleResponse
#define SOAP_TYPE_dss__Event_ScheduleResponse (187)
/* dss:Event-ScheduleResponse */
struct dss__Event_ScheduleResponse
{
public:
	int scheduledEventID;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Event_Schedule
#define SOAP_TYPE_dss__Event_Schedule (188)
/* dss:Event-Schedule */
struct dss__Event_Schedule
{
public:
	int _token;	/* required element of type xsd:int */
	char *_icalString;	/* optional element of type xsd:string */
	int _eventID;	/* required element of type xsd:int */
	Parameter _params;	/* required element of type Parameter */
};
#endif

#ifndef SOAP_TYPE_dss__Event_DeleteScheduleResponse
#define SOAP_TYPE_dss__Event_DeleteScheduleResponse (190)
/* dss:Event-DeleteScheduleResponse */
struct dss__Event_DeleteScheduleResponse
{
public:
	int result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__Event_DeleteSchedule
#define SOAP_TYPE_dss__Event_DeleteSchedule (191)
/* dss:Event-DeleteSchedule */
struct dss__Event_DeleteSchedule
{
public:
	int _token;	/* required element of type xsd:int */
	int _scheduleEventID;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (192)
/* SOAP Header: */
struct SOAP_ENV__Header
{
#ifdef WITH_NOEMPTYSTRUCT
private:
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (193)
/* SOAP Fault Code: */
struct SOAP_ENV__Code
{
public:
	char *SOAP_ENV__Value;	/* optional element of type xsd:QName */
	struct SOAP_ENV__Code *SOAP_ENV__Subcode;	/* optional element of type SOAP-ENV:Code */
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (195)
/* SOAP-ENV:Detail */
struct SOAP_ENV__Detail
{
public:
	int __type;	/* any type of element <fault> (defined below) */
	void *fault;	/* transient */
	char *__any;
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (198)
/* SOAP-ENV:Reason */
struct SOAP_ENV__Reason
{
public:
	char *SOAP_ENV__Text;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (199)
/* SOAP Fault: */
struct SOAP_ENV__Fault
{
public:
	char *faultcode;	/* optional element of type xsd:QName */
	char *faultstring;	/* optional element of type xsd:string */
	char *faultactor;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *detail;	/* optional element of type SOAP-ENV:Detail */
	struct SOAP_ENV__Code *SOAP_ENV__Code;	/* optional element of type SOAP-ENV:Code */
	struct SOAP_ENV__Reason *SOAP_ENV__Reason;	/* optional element of type SOAP-ENV:Reason */
	char *SOAP_ENV__Node;	/* optional element of type xsd:string */
	char *SOAP_ENV__Role;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *SOAP_ENV__Detail;	/* optional element of type SOAP-ENV:Detail */
};
#endif

/******************************************************************************\
 *                                                                            *
 * Types with Custom Serializers                                              *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Typedefs                                                                   *
 *                                                                            *
\******************************************************************************/

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
typedef char *_QName;
#endif

#ifndef SOAP_TYPE__XML
#define SOAP_TYPE__XML (6)
typedef char *_XML;
#endif

#ifndef SOAP_TYPE_DSID
#define SOAP_TYPE_DSID (13)
typedef LONG64 DSID;
#endif


/******************************************************************************\
 *                                                                            *
 * Typedef Synonyms                                                           *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Externals                                                                  *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Service Operations                                                         *
 *                                                                            *
\******************************************************************************/


SOAP_FMAC5 int SOAP_FMAC6 dss__Authenticate(struct soap*, char *_userName, char *_password, int &token);

SOAP_FMAC5 int SOAP_FMAC6 dss__SignOff(struct soap*, int _token, int &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__Apartment_CreateSetFromGroup(struct soap*, int _token, char *_groupName, int &setID);

SOAP_FMAC5 int SOAP_FMAC6 dss__Apartment_CreateSetFromDeviceIDs(struct soap*, int _token, IntArray _ids, int &setID);

SOAP_FMAC5 int SOAP_FMAC6 dss__Apartment_CreateSetFromDeviceNames(struct soap*, int _token, StringArray _names, int &setID);

SOAP_FMAC5 int SOAP_FMAC6 dss__Apartment_CreateEmptySet(struct soap*, int _token, int &setID);

SOAP_FMAC5 int SOAP_FMAC6 dss__Apartment_GetDevices(struct soap*, int _token, int &setID);

SOAP_FMAC5 int SOAP_FMAC6 dss__Apartment_GetDeviceIDByName(struct soap*, int _token, char *_deviceName, int &deviceID);

SOAP_FMAC5 int SOAP_FMAC6 dss__Set_AddDeviceByName(struct soap*, int _token, int _setID, char *_name, bool &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__Set_AddDeviceByID(struct soap*, int _token, int _setID, int _deviceID, bool &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__Set_RemoveDevice(struct soap*, int _token, int _setID, int _deviceID, bool &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__Set_Combine(struct soap*, int _token, int _setID1, int _setID2, int &setID);

SOAP_FMAC5 int SOAP_FMAC6 dss__Set_Remove(struct soap*, int _token, int _setID, int _setIDToRemove, int &setID);

SOAP_FMAC5 int SOAP_FMAC6 dss__Set_ByGroup(struct soap*, int _token, int _setID, int _groupID, int &setID);

SOAP_FMAC5 int SOAP_FMAC6 dss__Apartment_GetGroupByName(struct soap*, int _token, int _groupName, int &groupID);

SOAP_FMAC5 int SOAP_FMAC6 dss__Apartment_GetRoomByName(struct soap*, int _token, char *_roomName, int &roomID);

SOAP_FMAC5 int SOAP_FMAC6 dss__Apartment_GetRoomIDs(struct soap*, int _token, IntArray &roomIDs);

SOAP_FMAC5 int SOAP_FMAC6 dss__Set_TurnOn(struct soap*, int _token, int _setID, int &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__Set_TurnOff(struct soap*, int _token, int _setID, int &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__Set_IncreaseValue(struct soap*, int _token, int _setID, int _paramID, int &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__Set_DecreaseValue(struct soap*, int _token, int _setID, int _paramID, int &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__Set_Enable(struct soap*, int _token, int _setID, int &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__Set_Disable(struct soap*, int _token, int _setID, int &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__Set_StartDim(struct soap*, int _token, int _setID, bool _directionUp, int _paramID, int &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__Set_EndDim(struct soap*, int _token, int _setID, int _paramID, int &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__Set_SetValue(struct soap*, int _token, int _setID, float _value, int _paramID, int &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__Device_TurnOn(struct soap*, int _token, int _deviceID, int &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__Device_TurnOff(struct soap*, int _token, int _deviceID, int &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__Device_IncreaseValue(struct soap*, int _token, int _deviceID, int _paramID, int &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__Device_DecreaseValue(struct soap*, int _token, int _deviceID, int _paramID, int &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__Device_Enable(struct soap*, int _token, int _deviceID, int &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__Device_Disable(struct soap*, int _token, int _deviceID, int &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__Device_StartDim(struct soap*, int _token, int _deviceID, bool _directionUp, int _paramID, int &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__Device_EndDim(struct soap*, int _token, int _deviceID, int _paramID, int &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__Device_SetValue(struct soap*, int _token, int _deviceID, float _value, int _paramID, int &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__Device_GetValue(struct soap*, int _token, int _deviceID, float &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__Device_GetDSID(struct soap*, int _token, int _deviceID, LONG64 &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__Apartment_GetModulatorIDs(struct soap*, int _token, IntArray &ids);

SOAP_FMAC5 int SOAP_FMAC6 dss__Modulator_GetDSID(struct soap*, int _token, int _modulatorID, LONG64 &dsid);

SOAP_FMAC5 int SOAP_FMAC6 dss__Modulator_GetName(struct soap*, int _token, int _modulatorID, char **name);

SOAP_FMAC5 int SOAP_FMAC6 dss__Apartment_AllocateRoom(struct soap*, int _token, int &roomID);

SOAP_FMAC5 int SOAP_FMAC6 dss__Apartment_DeleteRoom(struct soap*, int _token, int _roomID, int &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__Room_AddDevice(struct soap*, int _token, int _roomID, int _deviceID, int &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__Room_RemoveDevice(struct soap*, int _token, int _roomID, int _deviceID, int &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__Room_SetName(struct soap*, int _token, int _roomID, char *_name, int &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__Apartment_AllocateUserGroup(struct soap*, int _token, int &groupID);

SOAP_FMAC5 int SOAP_FMAC6 dss__Group_RemoveUserGroup(struct soap*, int _token, int _groupID, int &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__Group_AddDevice(struct soap*, int _token, int _groupID, int _deviceID, int &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__Group_RemoveDevice(struct soap*, int _token, int _groupID, int _deviceID, int &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__Event_Raise(struct soap*, int _token, int _eventID, int _sourceID, Parameter _params, int &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__Event_GetActionNames(struct soap*, int _token, StringArray &names);

SOAP_FMAC5 int SOAP_FMAC6 dss__Event_GetActionParamsTemplate(struct soap*, int _token, char *_name, Parameter &paramsTemplate);

SOAP_FMAC5 int SOAP_FMAC6 dss__Event_Subscribe(struct soap*, int _token, IntArray _eventIDs, IntArray _sourceIDs, char *_actionName, Parameter _params, int &subscriptionID);

SOAP_FMAC5 int SOAP_FMAC6 dss__Event_Unsubscribe(struct soap*, int _token, int _subscriptionID, int &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__Event_Schedule(struct soap*, int _token, char *_icalString, int _eventID, Parameter _params, int &scheduledEventID);

SOAP_FMAC5 int SOAP_FMAC6 dss__Event_DeleteSchedule(struct soap*, int _token, int _scheduleEventID, int &result);

/******************************************************************************\
 *                                                                            *
 * Skeletons                                                                  *
 *                                                                            *
\******************************************************************************/

SOAP_FMAC5 int SOAP_FMAC6 soap_serve(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_request(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__Authenticate(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__SignOff(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__Apartment_CreateSetFromGroup(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__Apartment_CreateSetFromDeviceIDs(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__Apartment_CreateSetFromDeviceNames(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__Apartment_CreateEmptySet(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__Apartment_GetDevices(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__Apartment_GetDeviceIDByName(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__Set_AddDeviceByName(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__Set_AddDeviceByID(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__Set_RemoveDevice(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__Set_Combine(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__Set_Remove(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__Set_ByGroup(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__Apartment_GetGroupByName(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__Apartment_GetRoomByName(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__Apartment_GetRoomIDs(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__Set_TurnOn(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__Set_TurnOff(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__Set_IncreaseValue(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__Set_DecreaseValue(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__Set_Enable(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__Set_Disable(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__Set_StartDim(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__Set_EndDim(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__Set_SetValue(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__Device_TurnOn(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__Device_TurnOff(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__Device_IncreaseValue(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__Device_DecreaseValue(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__Device_Enable(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__Device_Disable(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__Device_StartDim(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__Device_EndDim(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__Device_SetValue(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__Device_GetValue(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__Device_GetDSID(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__Apartment_GetModulatorIDs(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__Modulator_GetDSID(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__Modulator_GetName(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__Apartment_AllocateRoom(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__Apartment_DeleteRoom(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__Room_AddDevice(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__Room_RemoveDevice(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__Room_SetName(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__Apartment_AllocateUserGroup(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__Group_RemoveUserGroup(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__Group_AddDevice(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__Group_RemoveDevice(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__Event_Raise(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__Event_GetActionNames(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__Event_GetActionParamsTemplate(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__Event_Subscribe(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__Event_Unsubscribe(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__Event_Schedule(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__Event_DeleteSchedule(struct soap*);

#endif

/* End of soapStub.h */
