/* soapStub.h
   Generated by gSOAP 2.7.15 from model_soap.h
   Copyright(C) 2000-2009, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef soapStub_H
#define soapStub_H
#include <deque>
#include <list>
#include <vector>
#include <set>
#include "stdsoap2.h"

/******************************************************************************\
 *                                                                            *
 * Enumerations                                                               *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Types with Custom Serializers                                              *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Classes and Structs                                                        *
 *                                                                            *
\******************************************************************************/


#if 0 /* volatile type: do not redeclare here */

#endif

#if 0 /* volatile type: do not redeclare here */

#endif

#ifndef SOAP_TYPE_dss__AuthenticateResponse
#define SOAP_TYPE_dss__AuthenticateResponse (21)
/* dss:AuthenticateResponse */
struct dss__AuthenticateResponse
{
public:
	std::string token;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_dss__Authenticate
#define SOAP_TYPE_dss__Authenticate (22)
/* dss:Authenticate */
struct dss__Authenticate
{
public:
	char *_userName;	/* optional element of type xsd:string */
	char *_password;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_dss__SignOffResponse
#define SOAP_TYPE_dss__SignOffResponse (25)
/* dss:SignOffResponse */
struct dss__SignOffResponse
{
public:
	int result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__SignOff
#define SOAP_TYPE_dss__SignOff (26)
/* dss:SignOff */
struct dss__SignOff
{
public:
	char *_token;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_dss__ApartmentCreateSetFromGroupResponse
#define SOAP_TYPE_dss__ApartmentCreateSetFromGroupResponse (28)
/* dss:ApartmentCreateSetFromGroupResponse */
struct dss__ApartmentCreateSetFromGroupResponse
{
public:
	std::string result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_dss__ApartmentCreateSetFromGroup
#define SOAP_TYPE_dss__ApartmentCreateSetFromGroup (29)
/* dss:ApartmentCreateSetFromGroup */
struct dss__ApartmentCreateSetFromGroup
{
public:
	char *_token;	/* optional element of type xsd:string */
	char *_groupName;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_dss__ApartmentCreateSetFromDeviceIDsResponse
#define SOAP_TYPE_dss__ApartmentCreateSetFromDeviceIDsResponse (32)
/* dss:ApartmentCreateSetFromDeviceIDsResponse */
struct dss__ApartmentCreateSetFromDeviceIDsResponse
{
public:
	std::string result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_dss__ApartmentCreateSetFromDeviceIDs
#define SOAP_TYPE_dss__ApartmentCreateSetFromDeviceIDs (33)
/* dss:ApartmentCreateSetFromDeviceIDs */
struct dss__ApartmentCreateSetFromDeviceIDs
{
public:
	char *_token;	/* optional element of type xsd:string */
	std::vector<std::string >_ids;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_dss__ApartmentCreateSetFromDeviceNamesResponse
#define SOAP_TYPE_dss__ApartmentCreateSetFromDeviceNamesResponse (35)
/* dss:ApartmentCreateSetFromDeviceNamesResponse */
struct dss__ApartmentCreateSetFromDeviceNamesResponse
{
public:
	std::string result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_dss__ApartmentCreateSetFromDeviceNames
#define SOAP_TYPE_dss__ApartmentCreateSetFromDeviceNames (36)
/* dss:ApartmentCreateSetFromDeviceNames */
struct dss__ApartmentCreateSetFromDeviceNames
{
public:
	char *_token;	/* optional element of type xsd:string */
	std::vector<std::string >_names;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_dss__ApartmentGetDevicesResponse
#define SOAP_TYPE_dss__ApartmentGetDevicesResponse (38)
/* dss:ApartmentGetDevicesResponse */
struct dss__ApartmentGetDevicesResponse
{
public:
	std::string result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_dss__ApartmentGetDevices
#define SOAP_TYPE_dss__ApartmentGetDevices (39)
/* dss:ApartmentGetDevices */
struct dss__ApartmentGetDevices
{
public:
	char *_token;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_dss__ApartmentGetDeviceIDByNameResponse
#define SOAP_TYPE_dss__ApartmentGetDeviceIDByNameResponse (41)
/* dss:ApartmentGetDeviceIDByNameResponse */
struct dss__ApartmentGetDeviceIDByNameResponse
{
public:
	std::string deviceID;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_dss__ApartmentGetDeviceIDByName
#define SOAP_TYPE_dss__ApartmentGetDeviceIDByName (42)
/* dss:ApartmentGetDeviceIDByName */
struct dss__ApartmentGetDeviceIDByName
{
public:
	char *_token;	/* optional element of type xsd:string */
	char *_deviceName;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_dss__ApartmentGetNameResponse
#define SOAP_TYPE_dss__ApartmentGetNameResponse (44)
/* dss:ApartmentGetNameResponse */
struct dss__ApartmentGetNameResponse
{
public:
	std::string result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_dss__ApartmentGetName
#define SOAP_TYPE_dss__ApartmentGetName (45)
/* dss:ApartmentGetName */
struct dss__ApartmentGetName
{
public:
	char *_token;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_dss__ApartmentSetNameResponse
#define SOAP_TYPE_dss__ApartmentSetNameResponse (49)
/* dss:ApartmentSetNameResponse */
struct dss__ApartmentSetNameResponse
{
public:
	bool result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:boolean */
};
#endif

#ifndef SOAP_TYPE_dss__ApartmentSetName
#define SOAP_TYPE_dss__ApartmentSetName (50)
/* dss:ApartmentSetName */
struct dss__ApartmentSetName
{
public:
	char *_token;	/* optional element of type xsd:string */
	char *_name;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_dss__SetAddDeviceByNameResponse
#define SOAP_TYPE_dss__SetAddDeviceByNameResponse (52)
/* dss:SetAddDeviceByNameResponse */
struct dss__SetAddDeviceByNameResponse
{
public:
	std::string result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_dss__SetAddDeviceByName
#define SOAP_TYPE_dss__SetAddDeviceByName (53)
/* dss:SetAddDeviceByName */
struct dss__SetAddDeviceByName
{
public:
	char *_token;	/* optional element of type xsd:string */
	char *_setSpec;	/* optional element of type xsd:string */
	char *_name;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_dss__SetAddDeviceByIDResponse
#define SOAP_TYPE_dss__SetAddDeviceByIDResponse (55)
/* dss:SetAddDeviceByIDResponse */
struct dss__SetAddDeviceByIDResponse
{
public:
	std::string result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_dss__SetAddDeviceByID
#define SOAP_TYPE_dss__SetAddDeviceByID (56)
/* dss:SetAddDeviceByID */
struct dss__SetAddDeviceByID
{
public:
	char *_token;	/* optional element of type xsd:string */
	char *_setSpec;	/* optional element of type xsd:string */
	char *_deviceID;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_dss__SetRemoveDeviceResponse
#define SOAP_TYPE_dss__SetRemoveDeviceResponse (58)
/* dss:SetRemoveDeviceResponse */
struct dss__SetRemoveDeviceResponse
{
public:
	std::string result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_dss__SetRemoveDevice
#define SOAP_TYPE_dss__SetRemoveDevice (59)
/* dss:SetRemoveDevice */
struct dss__SetRemoveDevice
{
public:
	char *_token;	/* optional element of type xsd:string */
	char *_setSpec;	/* optional element of type xsd:string */
	char *_deviceID;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_dss__SetCombineResponse
#define SOAP_TYPE_dss__SetCombineResponse (61)
/* dss:SetCombineResponse */
struct dss__SetCombineResponse
{
public:
	std::string result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_dss__SetCombine
#define SOAP_TYPE_dss__SetCombine (62)
/* dss:SetCombine */
struct dss__SetCombine
{
public:
	char *_token;	/* optional element of type xsd:string */
	char *_setSpec1;	/* optional element of type xsd:string */
	char *_setSpec2;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_dss__SetRemoveResponse
#define SOAP_TYPE_dss__SetRemoveResponse (64)
/* dss:SetRemoveResponse */
struct dss__SetRemoveResponse
{
public:
	std::string result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_dss__SetRemove
#define SOAP_TYPE_dss__SetRemove (65)
/* dss:SetRemove */
struct dss__SetRemove
{
public:
	char *_token;	/* optional element of type xsd:string */
	char *_setSpec;	/* optional element of type xsd:string */
	char *_setSpecToRemove;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_dss__SetByGroupResponse
#define SOAP_TYPE_dss__SetByGroupResponse (67)
/* dss:SetByGroupResponse */
struct dss__SetByGroupResponse
{
public:
	std::string result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_dss__SetByGroup
#define SOAP_TYPE_dss__SetByGroup (68)
/* dss:SetByGroup */
struct dss__SetByGroup
{
public:
	char *_token;	/* optional element of type xsd:string */
	char *_setSpec;	/* optional element of type xsd:string */
	int _groupID;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__SetGetContainedDevicesResponse
#define SOAP_TYPE_dss__SetGetContainedDevicesResponse (71)
/* dss:SetGetContainedDevicesResponse */
struct dss__SetGetContainedDevicesResponse
{
public:
	std::vector<std::string >deviceIDs;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_dss__SetGetContainedDevices
#define SOAP_TYPE_dss__SetGetContainedDevices (72)
/* dss:SetGetContainedDevices */
struct dss__SetGetContainedDevices
{
public:
	char *_token;	/* optional element of type xsd:string */
	char *_setSpec;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_dss__ApartmentGetGroupByNameResponse
#define SOAP_TYPE_dss__ApartmentGetGroupByNameResponse (74)
/* dss:ApartmentGetGroupByNameResponse */
struct dss__ApartmentGetGroupByNameResponse
{
public:
	int groupID;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__ApartmentGetGroupByName
#define SOAP_TYPE_dss__ApartmentGetGroupByName (75)
/* dss:ApartmentGetGroupByName */
struct dss__ApartmentGetGroupByName
{
public:
	char *_token;	/* optional element of type xsd:string */
	char *_groupName;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_dss__ApartmentGetZoneByNameResponse
#define SOAP_TYPE_dss__ApartmentGetZoneByNameResponse (77)
/* dss:ApartmentGetZoneByNameResponse */
struct dss__ApartmentGetZoneByNameResponse
{
public:
	int zoneID;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__ApartmentGetZoneByName
#define SOAP_TYPE_dss__ApartmentGetZoneByName (78)
/* dss:ApartmentGetZoneByName */
struct dss__ApartmentGetZoneByName
{
public:
	char *_token;	/* optional element of type xsd:string */
	char *_zoneName;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_dss__ApartmentGetZoneIDsResponse
#define SOAP_TYPE_dss__ApartmentGetZoneIDsResponse (82)
/* dss:ApartmentGetZoneIDsResponse */
struct dss__ApartmentGetZoneIDsResponse
{
public:
	std::vector<int >zoneIDs;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__ApartmentGetZoneIDs
#define SOAP_TYPE_dss__ApartmentGetZoneIDs (83)
/* dss:ApartmentGetZoneIDs */
struct dss__ApartmentGetZoneIDs
{
public:
	char *_token;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_dss__SetTurnOnResponse
#define SOAP_TYPE_dss__SetTurnOnResponse (85)
/* dss:SetTurnOnResponse */
struct dss__SetTurnOnResponse
{
public:
	bool result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:boolean */
};
#endif

#ifndef SOAP_TYPE_dss__SetTurnOn
#define SOAP_TYPE_dss__SetTurnOn (86)
/* dss:SetTurnOn */
struct dss__SetTurnOn
{
public:
	char *_token;	/* optional element of type xsd:string */
	char *_setSpec;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_dss__SetTurnOffResponse
#define SOAP_TYPE_dss__SetTurnOffResponse (88)
/* dss:SetTurnOffResponse */
struct dss__SetTurnOffResponse
{
public:
	bool result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:boolean */
};
#endif

#ifndef SOAP_TYPE_dss__SetTurnOff
#define SOAP_TYPE_dss__SetTurnOff (89)
/* dss:SetTurnOff */
struct dss__SetTurnOff
{
public:
	char *_token;	/* optional element of type xsd:string */
	char *_setSpec;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_dss__SetIncreaseValueResponse
#define SOAP_TYPE_dss__SetIncreaseValueResponse (91)
/* dss:SetIncreaseValueResponse */
struct dss__SetIncreaseValueResponse
{
public:
	bool result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:boolean */
};
#endif

#ifndef SOAP_TYPE_dss__SetIncreaseValue
#define SOAP_TYPE_dss__SetIncreaseValue (92)
/* dss:SetIncreaseValue */
struct dss__SetIncreaseValue
{
public:
	char *_token;	/* optional element of type xsd:string */
	char *_setSpec;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_dss__SetDecreaseValueResponse
#define SOAP_TYPE_dss__SetDecreaseValueResponse (94)
/* dss:SetDecreaseValueResponse */
struct dss__SetDecreaseValueResponse
{
public:
	bool result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:boolean */
};
#endif

#ifndef SOAP_TYPE_dss__SetDecreaseValue
#define SOAP_TYPE_dss__SetDecreaseValue (95)
/* dss:SetDecreaseValue */
struct dss__SetDecreaseValue
{
public:
	char *_token;	/* optional element of type xsd:string */
	char *_setSpec;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_dss__SetSetValueResponse
#define SOAP_TYPE_dss__SetSetValueResponse (98)
/* dss:SetSetValueResponse */
struct dss__SetSetValueResponse
{
public:
	bool result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:boolean */
};
#endif

#ifndef SOAP_TYPE_dss__SetSetValue
#define SOAP_TYPE_dss__SetSetValue (99)
/* dss:SetSetValue */
struct dss__SetSetValue
{
public:
	char *_token;	/* optional element of type xsd:string */
	char *_setSpec;	/* optional element of type xsd:string */
	double _value;	/* required element of type xsd:double */
};
#endif

#ifndef SOAP_TYPE_dss__SetCallSceneResponse
#define SOAP_TYPE_dss__SetCallSceneResponse (101)
/* dss:SetCallSceneResponse */
struct dss__SetCallSceneResponse
{
public:
	bool result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:boolean */
};
#endif

#ifndef SOAP_TYPE_dss__SetCallScene
#define SOAP_TYPE_dss__SetCallScene (102)
/* dss:SetCallScene */
struct dss__SetCallScene
{
public:
	char *_token;	/* optional element of type xsd:string */
	char *_setSpec;	/* optional element of type xsd:string */
	int _sceneNr;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__SetSaveSceneResponse
#define SOAP_TYPE_dss__SetSaveSceneResponse (104)
/* dss:SetSaveSceneResponse */
struct dss__SetSaveSceneResponse
{
public:
	bool result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:boolean */
};
#endif

#ifndef SOAP_TYPE_dss__SetSaveScene
#define SOAP_TYPE_dss__SetSaveScene (105)
/* dss:SetSaveScene */
struct dss__SetSaveScene
{
public:
	char *_token;	/* optional element of type xsd:string */
	char *_setSpec;	/* optional element of type xsd:string */
	int _sceneNr;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__ApartmentTurnOnResponse
#define SOAP_TYPE_dss__ApartmentTurnOnResponse (107)
/* dss:ApartmentTurnOnResponse */
struct dss__ApartmentTurnOnResponse
{
public:
	bool result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:boolean */
};
#endif

#ifndef SOAP_TYPE_dss__ApartmentTurnOn
#define SOAP_TYPE_dss__ApartmentTurnOn (108)
/* dss:ApartmentTurnOn */
struct dss__ApartmentTurnOn
{
public:
	char *_token;	/* optional element of type xsd:string */
	int _groupID;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__ApartmentTurnOffResponse
#define SOAP_TYPE_dss__ApartmentTurnOffResponse (110)
/* dss:ApartmentTurnOffResponse */
struct dss__ApartmentTurnOffResponse
{
public:
	bool result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:boolean */
};
#endif

#ifndef SOAP_TYPE_dss__ApartmentTurnOff
#define SOAP_TYPE_dss__ApartmentTurnOff (111)
/* dss:ApartmentTurnOff */
struct dss__ApartmentTurnOff
{
public:
	char *_token;	/* optional element of type xsd:string */
	int _groupID;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__ApartmentIncreaseValueResponse
#define SOAP_TYPE_dss__ApartmentIncreaseValueResponse (113)
/* dss:ApartmentIncreaseValueResponse */
struct dss__ApartmentIncreaseValueResponse
{
public:
	bool result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:boolean */
};
#endif

#ifndef SOAP_TYPE_dss__ApartmentIncreaseValue
#define SOAP_TYPE_dss__ApartmentIncreaseValue (114)
/* dss:ApartmentIncreaseValue */
struct dss__ApartmentIncreaseValue
{
public:
	char *_token;	/* optional element of type xsd:string */
	int _groupID;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__ApartmentDecreaseValueResponse
#define SOAP_TYPE_dss__ApartmentDecreaseValueResponse (116)
/* dss:ApartmentDecreaseValueResponse */
struct dss__ApartmentDecreaseValueResponse
{
public:
	bool result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:boolean */
};
#endif

#ifndef SOAP_TYPE_dss__ApartmentDecreaseValue
#define SOAP_TYPE_dss__ApartmentDecreaseValue (117)
/* dss:ApartmentDecreaseValue */
struct dss__ApartmentDecreaseValue
{
public:
	char *_token;	/* optional element of type xsd:string */
	int _groupID;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__ApartmentSetValueResponse
#define SOAP_TYPE_dss__ApartmentSetValueResponse (119)
/* dss:ApartmentSetValueResponse */
struct dss__ApartmentSetValueResponse
{
public:
	bool result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:boolean */
};
#endif

#ifndef SOAP_TYPE_dss__ApartmentSetValue
#define SOAP_TYPE_dss__ApartmentSetValue (120)
/* dss:ApartmentSetValue */
struct dss__ApartmentSetValue
{
public:
	char *_token;	/* optional element of type xsd:string */
	int _groupID;	/* required element of type xsd:int */
	double _value;	/* required element of type xsd:double */
};
#endif

#ifndef SOAP_TYPE_dss__ApartmentCallSceneResponse
#define SOAP_TYPE_dss__ApartmentCallSceneResponse (122)
/* dss:ApartmentCallSceneResponse */
struct dss__ApartmentCallSceneResponse
{
public:
	bool result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:boolean */
};
#endif

#ifndef SOAP_TYPE_dss__ApartmentCallScene
#define SOAP_TYPE_dss__ApartmentCallScene (123)
/* dss:ApartmentCallScene */
struct dss__ApartmentCallScene
{
public:
	char *_token;	/* optional element of type xsd:string */
	int _groupID;	/* required element of type xsd:int */
	int _sceneNr;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__ApartmentSaveSceneResponse
#define SOAP_TYPE_dss__ApartmentSaveSceneResponse (125)
/* dss:ApartmentSaveSceneResponse */
struct dss__ApartmentSaveSceneResponse
{
public:
	bool result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:boolean */
};
#endif

#ifndef SOAP_TYPE_dss__ApartmentSaveScene
#define SOAP_TYPE_dss__ApartmentSaveScene (126)
/* dss:ApartmentSaveScene */
struct dss__ApartmentSaveScene
{
public:
	char *_token;	/* optional element of type xsd:string */
	int _groupID;	/* required element of type xsd:int */
	int _sceneNr;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__ApartmentRescanResponse
#define SOAP_TYPE_dss__ApartmentRescanResponse (128)
/* dss:ApartmentRescanResponse */
struct dss__ApartmentRescanResponse
{
public:
	bool result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:boolean */
};
#endif

#ifndef SOAP_TYPE_dss__ApartmentRescan
#define SOAP_TYPE_dss__ApartmentRescan (129)
/* dss:ApartmentRescan */
struct dss__ApartmentRescan
{
public:
	char *_token;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_dss__CircuitRescanResponse
#define SOAP_TYPE_dss__CircuitRescanResponse (131)
/* dss:CircuitRescanResponse */
struct dss__CircuitRescanResponse
{
public:
	bool result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:boolean */
};
#endif

#ifndef SOAP_TYPE_dss__CircuitRescan
#define SOAP_TYPE_dss__CircuitRescan (132)
/* dss:CircuitRescan */
struct dss__CircuitRescan
{
public:
	char *_token;	/* optional element of type xsd:string */
	char *_dsid;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_dss__ZoneTurnOnResponse
#define SOAP_TYPE_dss__ZoneTurnOnResponse (134)
/* dss:ZoneTurnOnResponse */
struct dss__ZoneTurnOnResponse
{
public:
	bool result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:boolean */
};
#endif

#ifndef SOAP_TYPE_dss__ZoneTurnOn
#define SOAP_TYPE_dss__ZoneTurnOn (135)
/* dss:ZoneTurnOn */
struct dss__ZoneTurnOn
{
public:
	char *_token;	/* optional element of type xsd:string */
	int _zoneID;	/* required element of type xsd:int */
	int _groupID;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__ZoneTurnOffResponse
#define SOAP_TYPE_dss__ZoneTurnOffResponse (137)
/* dss:ZoneTurnOffResponse */
struct dss__ZoneTurnOffResponse
{
public:
	bool result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:boolean */
};
#endif

#ifndef SOAP_TYPE_dss__ZoneTurnOff
#define SOAP_TYPE_dss__ZoneTurnOff (138)
/* dss:ZoneTurnOff */
struct dss__ZoneTurnOff
{
public:
	char *_token;	/* optional element of type xsd:string */
	int _zoneID;	/* required element of type xsd:int */
	int _groupID;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__ZoneIncreaseValueResponse
#define SOAP_TYPE_dss__ZoneIncreaseValueResponse (140)
/* dss:ZoneIncreaseValueResponse */
struct dss__ZoneIncreaseValueResponse
{
public:
	bool result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:boolean */
};
#endif

#ifndef SOAP_TYPE_dss__ZoneIncreaseValue
#define SOAP_TYPE_dss__ZoneIncreaseValue (141)
/* dss:ZoneIncreaseValue */
struct dss__ZoneIncreaseValue
{
public:
	char *_token;	/* optional element of type xsd:string */
	int _zoneID;	/* required element of type xsd:int */
	int _groupID;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__ZoneDecreaseValueResponse
#define SOAP_TYPE_dss__ZoneDecreaseValueResponse (143)
/* dss:ZoneDecreaseValueResponse */
struct dss__ZoneDecreaseValueResponse
{
public:
	bool result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:boolean */
};
#endif

#ifndef SOAP_TYPE_dss__ZoneDecreaseValue
#define SOAP_TYPE_dss__ZoneDecreaseValue (144)
/* dss:ZoneDecreaseValue */
struct dss__ZoneDecreaseValue
{
public:
	char *_token;	/* optional element of type xsd:string */
	int _zoneID;	/* required element of type xsd:int */
	int _groupID;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__ZoneSetValueResponse
#define SOAP_TYPE_dss__ZoneSetValueResponse (146)
/* dss:ZoneSetValueResponse */
struct dss__ZoneSetValueResponse
{
public:
	bool result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:boolean */
};
#endif

#ifndef SOAP_TYPE_dss__ZoneSetValue
#define SOAP_TYPE_dss__ZoneSetValue (147)
/* dss:ZoneSetValue */
struct dss__ZoneSetValue
{
public:
	char *_token;	/* optional element of type xsd:string */
	int _zoneID;	/* required element of type xsd:int */
	int _groupID;	/* required element of type xsd:int */
	double _value;	/* required element of type xsd:double */
};
#endif

#ifndef SOAP_TYPE_dss__ZoneCallSceneResponse
#define SOAP_TYPE_dss__ZoneCallSceneResponse (149)
/* dss:ZoneCallSceneResponse */
struct dss__ZoneCallSceneResponse
{
public:
	bool result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:boolean */
};
#endif

#ifndef SOAP_TYPE_dss__ZoneCallScene
#define SOAP_TYPE_dss__ZoneCallScene (150)
/* dss:ZoneCallScene */
struct dss__ZoneCallScene
{
public:
	char *_token;	/* optional element of type xsd:string */
	int _zoneID;	/* required element of type xsd:int */
	int _groupID;	/* required element of type xsd:int */
	int _sceneNr;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__ZoneSaveSceneResponse
#define SOAP_TYPE_dss__ZoneSaveSceneResponse (152)
/* dss:ZoneSaveSceneResponse */
struct dss__ZoneSaveSceneResponse
{
public:
	bool result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:boolean */
};
#endif

#ifndef SOAP_TYPE_dss__ZoneSaveScene
#define SOAP_TYPE_dss__ZoneSaveScene (153)
/* dss:ZoneSaveScene */
struct dss__ZoneSaveScene
{
public:
	char *_token;	/* optional element of type xsd:string */
	int _zoneID;	/* required element of type xsd:int */
	int _groupID;	/* required element of type xsd:int */
	int _sceneNr;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__DeviceTurnOnResponse
#define SOAP_TYPE_dss__DeviceTurnOnResponse (155)
/* dss:DeviceTurnOnResponse */
struct dss__DeviceTurnOnResponse
{
public:
	bool result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:boolean */
};
#endif

#ifndef SOAP_TYPE_dss__DeviceTurnOn
#define SOAP_TYPE_dss__DeviceTurnOn (156)
/* dss:DeviceTurnOn */
struct dss__DeviceTurnOn
{
public:
	char *_token;	/* optional element of type xsd:string */
	char *_deviceID;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_dss__DeviceTurnOffResponse
#define SOAP_TYPE_dss__DeviceTurnOffResponse (158)
/* dss:DeviceTurnOffResponse */
struct dss__DeviceTurnOffResponse
{
public:
	bool result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:boolean */
};
#endif

#ifndef SOAP_TYPE_dss__DeviceTurnOff
#define SOAP_TYPE_dss__DeviceTurnOff (159)
/* dss:DeviceTurnOff */
struct dss__DeviceTurnOff
{
public:
	char *_token;	/* optional element of type xsd:string */
	char *_deviceID;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_dss__DeviceIncreaseValueResponse
#define SOAP_TYPE_dss__DeviceIncreaseValueResponse (161)
/* dss:DeviceIncreaseValueResponse */
struct dss__DeviceIncreaseValueResponse
{
public:
	bool result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:boolean */
};
#endif

#ifndef SOAP_TYPE_dss__DeviceIncreaseValue
#define SOAP_TYPE_dss__DeviceIncreaseValue (162)
/* dss:DeviceIncreaseValue */
struct dss__DeviceIncreaseValue
{
public:
	char *_token;	/* optional element of type xsd:string */
	char *_deviceID;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_dss__DeviceDecreaseValueResponse
#define SOAP_TYPE_dss__DeviceDecreaseValueResponse (164)
/* dss:DeviceDecreaseValueResponse */
struct dss__DeviceDecreaseValueResponse
{
public:
	bool result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:boolean */
};
#endif

#ifndef SOAP_TYPE_dss__DeviceDecreaseValue
#define SOAP_TYPE_dss__DeviceDecreaseValue (165)
/* dss:DeviceDecreaseValue */
struct dss__DeviceDecreaseValue
{
public:
	char *_token;	/* optional element of type xsd:string */
	char *_deviceID;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_dss__DeviceSetValueResponse
#define SOAP_TYPE_dss__DeviceSetValueResponse (167)
/* dss:DeviceSetValueResponse */
struct dss__DeviceSetValueResponse
{
public:
	bool result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:boolean */
};
#endif

#ifndef SOAP_TYPE_dss__DeviceSetValue
#define SOAP_TYPE_dss__DeviceSetValue (168)
/* dss:DeviceSetValue */
struct dss__DeviceSetValue
{
public:
	char *_token;	/* optional element of type xsd:string */
	char *_deviceID;	/* optional element of type xsd:string */
	double _value;	/* required element of type xsd:double */
};
#endif

#ifndef SOAP_TYPE_dss__DeviceGetValueResponse
#define SOAP_TYPE_dss__DeviceGetValueResponse (171)
/* dss:DeviceGetValueResponse */
struct dss__DeviceGetValueResponse
{
public:
	double result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:double */
};
#endif

#ifndef SOAP_TYPE_dss__DeviceGetValue
#define SOAP_TYPE_dss__DeviceGetValue (172)
/* dss:DeviceGetValue */
struct dss__DeviceGetValue
{
public:
	char *_token;	/* optional element of type xsd:string */
	char *_deviceID;	/* optional element of type xsd:string */
	int _paramID;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__DeviceCallSceneResponse
#define SOAP_TYPE_dss__DeviceCallSceneResponse (174)
/* dss:DeviceCallSceneResponse */
struct dss__DeviceCallSceneResponse
{
public:
	bool result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:boolean */
};
#endif

#ifndef SOAP_TYPE_dss__DeviceCallScene
#define SOAP_TYPE_dss__DeviceCallScene (175)
/* dss:DeviceCallScene */
struct dss__DeviceCallScene
{
public:
	char *_token;	/* optional element of type xsd:string */
	char *_deviceID;	/* optional element of type xsd:string */
	int _sceneNr;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__DeviceSaveSceneResponse
#define SOAP_TYPE_dss__DeviceSaveSceneResponse (177)
/* dss:DeviceSaveSceneResponse */
struct dss__DeviceSaveSceneResponse
{
public:
	bool result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:boolean */
};
#endif

#ifndef SOAP_TYPE_dss__DeviceSaveScene
#define SOAP_TYPE_dss__DeviceSaveScene (178)
/* dss:DeviceSaveScene */
struct dss__DeviceSaveScene
{
public:
	char *_token;	/* optional element of type xsd:string */
	char *_deviceID;	/* optional element of type xsd:string */
	int _sceneNr;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__DeviceGetNameResponse
#define SOAP_TYPE_dss__DeviceGetNameResponse (181)
/* dss:DeviceGetNameResponse */
struct dss__DeviceGetNameResponse
{
public:
	char **result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_dss__DeviceGetName
#define SOAP_TYPE_dss__DeviceGetName (182)
/* dss:DeviceGetName */
struct dss__DeviceGetName
{
public:
	char *_token;	/* optional element of type xsd:string */
	char *_deviceID;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_dss__DeviceSetNameResponse
#define SOAP_TYPE_dss__DeviceSetNameResponse (184)
/* dss:DeviceSetNameResponse */
struct dss__DeviceSetNameResponse
{
public:
	bool result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:boolean */
};
#endif

#ifndef SOAP_TYPE_dss__DeviceSetName
#define SOAP_TYPE_dss__DeviceSetName (185)
/* dss:DeviceSetName */
struct dss__DeviceSetName
{
public:
	char *_token;	/* optional element of type xsd:string */
	char *_deviceID;	/* optional element of type xsd:string */
	char *_name;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_dss__DeviceGetZoneIDResponse
#define SOAP_TYPE_dss__DeviceGetZoneIDResponse (187)
/* dss:DeviceGetZoneIDResponse */
struct dss__DeviceGetZoneIDResponse
{
public:
	int result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__DeviceGetZoneID
#define SOAP_TYPE_dss__DeviceGetZoneID (188)
/* dss:DeviceGetZoneID */
struct dss__DeviceGetZoneID
{
public:
	char *_token;	/* optional element of type xsd:string */
	char *_deviceID;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_dss__DeviceAddTagResponse
#define SOAP_TYPE_dss__DeviceAddTagResponse (190)
/* dss:DeviceAddTagResponse */
struct dss__DeviceAddTagResponse
{
public:
	bool result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:boolean */
};
#endif

#ifndef SOAP_TYPE_dss__DeviceAddTag
#define SOAP_TYPE_dss__DeviceAddTag (191)
/* dss:DeviceAddTag */
struct dss__DeviceAddTag
{
public:
	char *_token;	/* optional element of type xsd:string */
	char *_deviceID;	/* optional element of type xsd:string */
	char *_tag;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_dss__DeviceRemoveTagResponse
#define SOAP_TYPE_dss__DeviceRemoveTagResponse (193)
/* dss:DeviceRemoveTagResponse */
struct dss__DeviceRemoveTagResponse
{
public:
	bool result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:boolean */
};
#endif

#ifndef SOAP_TYPE_dss__DeviceRemoveTag
#define SOAP_TYPE_dss__DeviceRemoveTag (194)
/* dss:DeviceRemoveTag */
struct dss__DeviceRemoveTag
{
public:
	char *_token;	/* optional element of type xsd:string */
	char *_deviceID;	/* optional element of type xsd:string */
	char *_tag;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_dss__DeviceHasTagResponse
#define SOAP_TYPE_dss__DeviceHasTagResponse (196)
/* dss:DeviceHasTagResponse */
struct dss__DeviceHasTagResponse
{
public:
	bool result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:boolean */
};
#endif

#ifndef SOAP_TYPE_dss__DeviceHasTag
#define SOAP_TYPE_dss__DeviceHasTag (197)
/* dss:DeviceHasTag */
struct dss__DeviceHasTag
{
public:
	char *_token;	/* optional element of type xsd:string */
	char *_deviceID;	/* optional element of type xsd:string */
	char *_tag;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_dss__DeviceGetTagsResponse
#define SOAP_TYPE_dss__DeviceGetTagsResponse (199)
/* dss:DeviceGetTagsResponse */
struct dss__DeviceGetTagsResponse
{
public:
	std::vector<std::string >result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_dss__DeviceGetTags
#define SOAP_TYPE_dss__DeviceGetTags (200)
/* dss:DeviceGetTags */
struct dss__DeviceGetTags
{
public:
	char *_token;	/* optional element of type xsd:string */
	char *_deviceID;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_dss__DeviceLockResponse
#define SOAP_TYPE_dss__DeviceLockResponse (202)
/* dss:DeviceLockResponse */
struct dss__DeviceLockResponse
{
public:
	bool result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:boolean */
};
#endif

#ifndef SOAP_TYPE_dss__DeviceLock
#define SOAP_TYPE_dss__DeviceLock (203)
/* dss:DeviceLock */
struct dss__DeviceLock
{
public:
	char *_token;	/* optional element of type xsd:string */
	char *_deviceID;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_dss__DeviceUnlockResponse
#define SOAP_TYPE_dss__DeviceUnlockResponse (205)
/* dss:DeviceUnlockResponse */
struct dss__DeviceUnlockResponse
{
public:
	bool result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:boolean */
};
#endif

#ifndef SOAP_TYPE_dss__DeviceUnlock
#define SOAP_TYPE_dss__DeviceUnlock (206)
/* dss:DeviceUnlock */
struct dss__DeviceUnlock
{
public:
	char *_token;	/* optional element of type xsd:string */
	char *_deviceID;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_dss__DeviceGetIsLockedResponse
#define SOAP_TYPE_dss__DeviceGetIsLockedResponse (208)
/* dss:DeviceGetIsLockedResponse */
struct dss__DeviceGetIsLockedResponse
{
public:
	bool result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:boolean */
};
#endif

#ifndef SOAP_TYPE_dss__DeviceGetIsLocked
#define SOAP_TYPE_dss__DeviceGetIsLocked (209)
/* dss:DeviceGetIsLocked */
struct dss__DeviceGetIsLocked
{
public:
	char *_token;	/* optional element of type xsd:string */
	char *_deviceID;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_dss__DSMeterGetPowerConsumptionResponse
#define SOAP_TYPE_dss__DSMeterGetPowerConsumptionResponse (212)
/* dss:DSMeterGetPowerConsumptionResponse */
struct dss__DSMeterGetPowerConsumptionResponse
{
public:
	unsigned long result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:unsignedInt */
};
#endif

#ifndef SOAP_TYPE_dss__DSMeterGetPowerConsumption
#define SOAP_TYPE_dss__DSMeterGetPowerConsumption (213)
/* dss:DSMeterGetPowerConsumption */
struct dss__DSMeterGetPowerConsumption
{
public:
	char *_token;	/* optional element of type xsd:string */
	char *_dsMeterID;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_dss__ApartmentGetDSMeterIDsResponse
#define SOAP_TYPE_dss__ApartmentGetDSMeterIDsResponse (215)
/* dss:ApartmentGetDSMeterIDsResponse */
struct dss__ApartmentGetDSMeterIDsResponse
{
public:
	std::vector<std::string >ids;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_dss__ApartmentGetDSMeterIDs
#define SOAP_TYPE_dss__ApartmentGetDSMeterIDs (216)
/* dss:ApartmentGetDSMeterIDs */
struct dss__ApartmentGetDSMeterIDs
{
public:
	char *_token;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_dss__DSMeterGetNameResponse
#define SOAP_TYPE_dss__DSMeterGetNameResponse (218)
/* dss:DSMeterGetNameResponse */
struct dss__DSMeterGetNameResponse
{
public:
	std::string name;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_dss__DSMeterGetName
#define SOAP_TYPE_dss__DSMeterGetName (219)
/* dss:DSMeterGetName */
struct dss__DSMeterGetName
{
public:
	char *_token;	/* optional element of type xsd:string */
	char *_dsMeterID;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_dss__DSMeterSetNameResponse
#define SOAP_TYPE_dss__DSMeterSetNameResponse (221)
/* dss:DSMeterSetNameResponse */
struct dss__DSMeterSetNameResponse
{
public:
	bool result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:boolean */
};
#endif

#ifndef SOAP_TYPE_dss__DSMeterSetName
#define SOAP_TYPE_dss__DSMeterSetName (222)
/* dss:DSMeterSetName */
struct dss__DSMeterSetName
{
public:
	char *_token;	/* optional element of type xsd:string */
	char *_dsMeterID;	/* optional element of type xsd:string */
	char *_name;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_dss__ApartmentAllocateZoneResponse
#define SOAP_TYPE_dss__ApartmentAllocateZoneResponse (224)
/* dss:ApartmentAllocateZoneResponse */
struct dss__ApartmentAllocateZoneResponse
{
public:
	int zoneID;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__ApartmentAllocateZone
#define SOAP_TYPE_dss__ApartmentAllocateZone (225)
/* dss:ApartmentAllocateZone */
struct dss__ApartmentAllocateZone
{
public:
	char *_token;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_dss__ApartmentDeleteZoneResponse
#define SOAP_TYPE_dss__ApartmentDeleteZoneResponse (227)
/* dss:ApartmentDeleteZoneResponse */
struct dss__ApartmentDeleteZoneResponse
{
public:
	int result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__ApartmentDeleteZone
#define SOAP_TYPE_dss__ApartmentDeleteZone (228)
/* dss:ApartmentDeleteZone */
struct dss__ApartmentDeleteZone
{
public:
	char *_token;	/* optional element of type xsd:string */
	int _zoneID;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__ZoneSetNameResponse
#define SOAP_TYPE_dss__ZoneSetNameResponse (230)
/* dss:ZoneSetNameResponse */
struct dss__ZoneSetNameResponse
{
public:
	bool result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:boolean */
};
#endif

#ifndef SOAP_TYPE_dss__ZoneSetName
#define SOAP_TYPE_dss__ZoneSetName (231)
/* dss:ZoneSetName */
struct dss__ZoneSetName
{
public:
	char *_token;	/* optional element of type xsd:string */
	int _zoneID;	/* required element of type xsd:int */
	char *_name;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_dss__ZoneGetNameResponse
#define SOAP_TYPE_dss__ZoneGetNameResponse (233)
/* dss:ZoneGetNameResponse */
struct dss__ZoneGetNameResponse
{
public:
	std::string result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_dss__ZoneGetName
#define SOAP_TYPE_dss__ZoneGetName (234)
/* dss:ZoneGetName */
struct dss__ZoneGetName
{
public:
	char *_token;	/* optional element of type xsd:string */
	int _zoneID;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__GroupSetNameResponse
#define SOAP_TYPE_dss__GroupSetNameResponse (236)
/* dss:GroupSetNameResponse */
struct dss__GroupSetNameResponse
{
public:
	bool result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:boolean */
};
#endif

#ifndef SOAP_TYPE_dss__GroupSetName
#define SOAP_TYPE_dss__GroupSetName (237)
/* dss:GroupSetName */
struct dss__GroupSetName
{
public:
	char *_token;	/* optional element of type xsd:string */
	int _zoneID;	/* required element of type xsd:int */
	int _groupID;	/* required element of type xsd:int */
	char *_name;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_dss__GroupGetNameResponse
#define SOAP_TYPE_dss__GroupGetNameResponse (239)
/* dss:GroupGetNameResponse */
struct dss__GroupGetNameResponse
{
public:
	std::string result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_dss__GroupGetName
#define SOAP_TYPE_dss__GroupGetName (240)
/* dss:GroupGetName */
struct dss__GroupGetName
{
public:
	char *_token;	/* optional element of type xsd:string */
	int _zoneID;	/* required element of type xsd:int */
	int _groupID;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__DeviceGetFunctionIDResponse
#define SOAP_TYPE_dss__DeviceGetFunctionIDResponse (242)
/* dss:DeviceGetFunctionIDResponse */
struct dss__DeviceGetFunctionIDResponse
{
public:
	int result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__DeviceGetFunctionID
#define SOAP_TYPE_dss__DeviceGetFunctionID (243)
/* dss:DeviceGetFunctionID */
struct dss__DeviceGetFunctionID
{
public:
	char *_token;	/* optional element of type xsd:string */
	char *_deviceID;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_dss__Event
#define SOAP_TYPE_dss__Event (244)
/* dss:Event */
class SOAP_CMAC dss__Event
{
public:
	std::string name;	/* required element of type xsd:string */
	std::vector<std::string >parameter;	/* optional element of type xsd:string */
public:
	virtual int soap_type() const { return 244; } /* = unique id SOAP_TYPE_dss__Event */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         dss__Event()  { this->soap_default(NULL); }
	virtual ~dss__Event() { }
};
#endif

#ifndef SOAP_TYPE_dss__EventRaiseResponse
#define SOAP_TYPE_dss__EventRaiseResponse (246)
/* dss:EventRaiseResponse */
struct dss__EventRaiseResponse
{
public:
	bool result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:boolean */
};
#endif

#ifndef SOAP_TYPE_dss__EventRaise
#define SOAP_TYPE_dss__EventRaise (247)
/* dss:EventRaise */
struct dss__EventRaise
{
public:
	char *_token;	/* optional element of type xsd:string */
	char *_eventName;	/* optional element of type xsd:string */
	char *_context;	/* optional element of type xsd:string */
	char *_parameter;	/* optional element of type xsd:string */
	char *_location;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_dss__EventWaitForResponse
#define SOAP_TYPE_dss__EventWaitForResponse (251)
/* dss:EventWaitForResponse */
struct dss__EventWaitForResponse
{
public:
	std::vector<dss__Event >result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type dss:Event */
};
#endif

#ifndef SOAP_TYPE_dss__EventWaitFor
#define SOAP_TYPE_dss__EventWaitFor (252)
/* dss:EventWaitFor */
struct dss__EventWaitFor
{
public:
	char *_token;	/* optional element of type xsd:string */
	int _timeout;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__EventSubscribeToResponse
#define SOAP_TYPE_dss__EventSubscribeToResponse (254)
/* dss:EventSubscribeToResponse */
struct dss__EventSubscribeToResponse
{
public:
	std::string result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_dss__EventSubscribeTo
#define SOAP_TYPE_dss__EventSubscribeTo (255)
/* dss:EventSubscribeTo */
struct dss__EventSubscribeTo
{
public:
	char *_token;	/* optional element of type xsd:string */
	std::string _name;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_dss__PropertyGetTypeResponse
#define SOAP_TYPE_dss__PropertyGetTypeResponse (257)
/* dss:PropertyGetTypeResponse */
struct dss__PropertyGetTypeResponse
{
public:
	std::string result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_dss__PropertyGetType
#define SOAP_TYPE_dss__PropertyGetType (258)
/* dss:PropertyGetType */
struct dss__PropertyGetType
{
public:
	char *_token;	/* optional element of type xsd:string */
	std::string _propertyName;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_dss__PropertySetIntResponse
#define SOAP_TYPE_dss__PropertySetIntResponse (260)
/* dss:PropertySetIntResponse */
struct dss__PropertySetIntResponse
{
public:
	bool result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:boolean */
};
#endif

#ifndef SOAP_TYPE_dss__PropertySetInt
#define SOAP_TYPE_dss__PropertySetInt (261)
/* dss:PropertySetInt */
struct dss__PropertySetInt
{
public:
	char *_token;	/* optional element of type xsd:string */
	std::string _propertyName;	/* required element of type xsd:string */
	int _value;	/* required element of type xsd:int */
	bool _mayCreate;	/* required element of type xsd:boolean */
};
#endif

#ifndef SOAP_TYPE_dss__PropertySetStringResponse
#define SOAP_TYPE_dss__PropertySetStringResponse (263)
/* dss:PropertySetStringResponse */
struct dss__PropertySetStringResponse
{
public:
	bool result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:boolean */
};
#endif

#ifndef SOAP_TYPE_dss__PropertySetString
#define SOAP_TYPE_dss__PropertySetString (264)
/* dss:PropertySetString */
struct dss__PropertySetString
{
public:
	char *_token;	/* optional element of type xsd:string */
	std::string _propertyName;	/* required element of type xsd:string */
	char *_value;	/* optional element of type xsd:string */
	bool _mayCreate;	/* required element of type xsd:boolean */
};
#endif

#ifndef SOAP_TYPE_dss__PropertySetBoolResponse
#define SOAP_TYPE_dss__PropertySetBoolResponse (266)
/* dss:PropertySetBoolResponse */
struct dss__PropertySetBoolResponse
{
public:
	bool result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:boolean */
};
#endif

#ifndef SOAP_TYPE_dss__PropertySetBool
#define SOAP_TYPE_dss__PropertySetBool (267)
/* dss:PropertySetBool */
struct dss__PropertySetBool
{
public:
	char *_token;	/* optional element of type xsd:string */
	std::string _propertyName;	/* required element of type xsd:string */
	bool _value;	/* required element of type xsd:boolean */
	bool _mayCreate;	/* required element of type xsd:boolean */
};
#endif

#ifndef SOAP_TYPE_dss__PropertyGetIntResponse
#define SOAP_TYPE_dss__PropertyGetIntResponse (269)
/* dss:PropertyGetIntResponse */
struct dss__PropertyGetIntResponse
{
public:
	int result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_dss__PropertyGetInt
#define SOAP_TYPE_dss__PropertyGetInt (270)
/* dss:PropertyGetInt */
struct dss__PropertyGetInt
{
public:
	char *_token;	/* optional element of type xsd:string */
	std::string _propertyName;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_dss__PropertyGetStringResponse
#define SOAP_TYPE_dss__PropertyGetStringResponse (272)
/* dss:PropertyGetStringResponse */
struct dss__PropertyGetStringResponse
{
public:
	std::string result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_dss__PropertyGetString
#define SOAP_TYPE_dss__PropertyGetString (273)
/* dss:PropertyGetString */
struct dss__PropertyGetString
{
public:
	char *_token;	/* optional element of type xsd:string */
	std::string _propertyName;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_dss__PropertyGetBoolResponse
#define SOAP_TYPE_dss__PropertyGetBoolResponse (275)
/* dss:PropertyGetBoolResponse */
struct dss__PropertyGetBoolResponse
{
public:
	bool result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:boolean */
};
#endif

#ifndef SOAP_TYPE_dss__PropertyGetBool
#define SOAP_TYPE_dss__PropertyGetBool (276)
/* dss:PropertyGetBool */
struct dss__PropertyGetBool
{
public:
	char *_token;	/* optional element of type xsd:string */
	std::string _propertyName;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_dss__PropertyGetChildrenResponse
#define SOAP_TYPE_dss__PropertyGetChildrenResponse (278)
/* dss:PropertyGetChildrenResponse */
struct dss__PropertyGetChildrenResponse
{
public:
	std::vector<std::string >result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_dss__PropertyGetChildren
#define SOAP_TYPE_dss__PropertyGetChildren (279)
/* dss:PropertyGetChildren */
struct dss__PropertyGetChildren
{
public:
	char *_token;	/* optional element of type xsd:string */
	std::string _propertyName;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_dss__StructureAddDeviceToZoneResponse
#define SOAP_TYPE_dss__StructureAddDeviceToZoneResponse (281)
/* dss:StructureAddDeviceToZoneResponse */
struct dss__StructureAddDeviceToZoneResponse
{
public:
	bool result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:boolean */
};
#endif

#ifndef SOAP_TYPE_dss__StructureAddDeviceToZone
#define SOAP_TYPE_dss__StructureAddDeviceToZone (282)
/* dss:StructureAddDeviceToZone */
struct dss__StructureAddDeviceToZone
{
public:
	char *_token;	/* optional element of type xsd:string */
	char *_deviceID;	/* optional element of type xsd:string */
	int _zoneID;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (283)
/* SOAP Header: */
struct SOAP_ENV__Header
{
#ifdef WITH_NOEMPTYSTRUCT
private:
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (284)
/* SOAP Fault Code: */
struct SOAP_ENV__Code
{
public:
	char *SOAP_ENV__Value;	/* optional element of type xsd:QName */
	struct SOAP_ENV__Code *SOAP_ENV__Subcode;	/* optional element of type SOAP-ENV:Code */
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (286)
/* SOAP-ENV:Detail */
struct SOAP_ENV__Detail
{
public:
	int __type;	/* any type of element <fault> (defined below) */
	void *fault;	/* transient */
	char *__any;
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (289)
/* SOAP-ENV:Reason */
struct SOAP_ENV__Reason
{
public:
	char *SOAP_ENV__Text;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (290)
/* SOAP Fault: */
struct SOAP_ENV__Fault
{
public:
	char *faultcode;	/* optional element of type xsd:QName */
	char *faultstring;	/* optional element of type xsd:string */
	char *faultactor;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *detail;	/* optional element of type SOAP-ENV:Detail */
	struct SOAP_ENV__Code *SOAP_ENV__Code;	/* optional element of type SOAP-ENV:Code */
	struct SOAP_ENV__Reason *SOAP_ENV__Reason;	/* optional element of type SOAP-ENV:Reason */
	char *SOAP_ENV__Node;	/* optional element of type xsd:string */
	char *SOAP_ENV__Role;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *SOAP_ENV__Detail;	/* optional element of type SOAP-ENV:Detail */
};
#endif

/******************************************************************************\
 *                                                                            *
 * Typedefs                                                                   *
 *                                                                            *
\******************************************************************************/

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
typedef char *_QName;
#endif

#ifndef SOAP_TYPE__XML
#define SOAP_TYPE__XML (6)
typedef char *_XML;
#endif

#ifndef SOAP_TYPE_xsd__unsignedInt
#define SOAP_TYPE_xsd__unsignedInt (14)
typedef unsigned long xsd__unsignedInt;
#endif

#ifndef SOAP_TYPE_xsd__unsignedLong
#define SOAP_TYPE_xsd__unsignedLong (17)
typedef ULONG64 xsd__unsignedLong;
#endif


/******************************************************************************\
 *                                                                            *
 * Externals                                                                  *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Service Operations                                                         *
 *                                                                            *
\******************************************************************************/


SOAP_FMAC5 int SOAP_FMAC6 dss__Authenticate(struct soap*, char *_userName, char *_password, std::string &token);

SOAP_FMAC5 int SOAP_FMAC6 dss__SignOff(struct soap*, char *_token, int &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__ApartmentCreateSetFromGroup(struct soap*, char *_token, char *_groupName, std::string &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__ApartmentCreateSetFromDeviceIDs(struct soap*, char *_token, std::vector<std::string >_ids, std::string &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__ApartmentCreateSetFromDeviceNames(struct soap*, char *_token, std::vector<std::string >_names, std::string &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__ApartmentGetDevices(struct soap*, char *_token, std::string &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__ApartmentGetDeviceIDByName(struct soap*, char *_token, char *_deviceName, std::string &deviceID);

SOAP_FMAC5 int SOAP_FMAC6 dss__ApartmentGetName(struct soap*, char *_token, std::string &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__ApartmentSetName(struct soap*, char *_token, char *_name, bool &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__SetAddDeviceByName(struct soap*, char *_token, char *_setSpec, char *_name, std::string &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__SetAddDeviceByID(struct soap*, char *_token, char *_setSpec, char *_deviceID, std::string &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__SetRemoveDevice(struct soap*, char *_token, char *_setSpec, char *_deviceID, std::string &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__SetCombine(struct soap*, char *_token, char *_setSpec1, char *_setSpec2, std::string &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__SetRemove(struct soap*, char *_token, char *_setSpec, char *_setSpecToRemove, std::string &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__SetByGroup(struct soap*, char *_token, char *_setSpec, int _groupID, std::string &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__SetGetContainedDevices(struct soap*, char *_token, char *_setSpec, std::vector<std::string >&deviceIDs);

SOAP_FMAC5 int SOAP_FMAC6 dss__ApartmentGetGroupByName(struct soap*, char *_token, char *_groupName, int &groupID);

SOAP_FMAC5 int SOAP_FMAC6 dss__ApartmentGetZoneByName(struct soap*, char *_token, char *_zoneName, int &zoneID);

SOAP_FMAC5 int SOAP_FMAC6 dss__ApartmentGetZoneIDs(struct soap*, char *_token, std::vector<int >&zoneIDs);

SOAP_FMAC5 int SOAP_FMAC6 dss__SetTurnOn(struct soap*, char *_token, char *_setSpec, bool &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__SetTurnOff(struct soap*, char *_token, char *_setSpec, bool &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__SetIncreaseValue(struct soap*, char *_token, char *_setSpec, bool &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__SetDecreaseValue(struct soap*, char *_token, char *_setSpec, bool &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__SetSetValue(struct soap*, char *_token, char *_setSpec, double _value, bool &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__SetCallScene(struct soap*, char *_token, char *_setSpec, int _sceneNr, bool &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__SetSaveScene(struct soap*, char *_token, char *_setSpec, int _sceneNr, bool &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__ApartmentTurnOn(struct soap*, char *_token, int _groupID, bool &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__ApartmentTurnOff(struct soap*, char *_token, int _groupID, bool &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__ApartmentIncreaseValue(struct soap*, char *_token, int _groupID, bool &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__ApartmentDecreaseValue(struct soap*, char *_token, int _groupID, bool &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__ApartmentSetValue(struct soap*, char *_token, int _groupID, double _value, bool &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__ApartmentCallScene(struct soap*, char *_token, int _groupID, int _sceneNr, bool &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__ApartmentSaveScene(struct soap*, char *_token, int _groupID, int _sceneNr, bool &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__ApartmentRescan(struct soap*, char *_token, bool &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__CircuitRescan(struct soap*, char *_token, char *_dsid, bool &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__ZoneTurnOn(struct soap*, char *_token, int _zoneID, int _groupID, bool &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__ZoneTurnOff(struct soap*, char *_token, int _zoneID, int _groupID, bool &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__ZoneIncreaseValue(struct soap*, char *_token, int _zoneID, int _groupID, bool &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__ZoneDecreaseValue(struct soap*, char *_token, int _zoneID, int _groupID, bool &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__ZoneSetValue(struct soap*, char *_token, int _zoneID, int _groupID, double _value, bool &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__ZoneCallScene(struct soap*, char *_token, int _zoneID, int _groupID, int _sceneNr, bool &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__ZoneSaveScene(struct soap*, char *_token, int _zoneID, int _groupID, int _sceneNr, bool &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__DeviceTurnOn(struct soap*, char *_token, char *_deviceID, bool &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__DeviceTurnOff(struct soap*, char *_token, char *_deviceID, bool &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__DeviceIncreaseValue(struct soap*, char *_token, char *_deviceID, bool &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__DeviceDecreaseValue(struct soap*, char *_token, char *_deviceID, bool &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__DeviceSetValue(struct soap*, char *_token, char *_deviceID, double _value, bool &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__DeviceGetValue(struct soap*, char *_token, char *_deviceID, int _paramID, double &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__DeviceCallScene(struct soap*, char *_token, char *_deviceID, int _sceneNr, bool &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__DeviceSaveScene(struct soap*, char *_token, char *_deviceID, int _sceneNr, bool &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__DeviceGetName(struct soap*, char *_token, char *_deviceID, char **result);

SOAP_FMAC5 int SOAP_FMAC6 dss__DeviceSetName(struct soap*, char *_token, char *_deviceID, char *_name, bool &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__DeviceGetZoneID(struct soap*, char *_token, char *_deviceID, int &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__DeviceAddTag(struct soap*, char *_token, char *_deviceID, char *_tag, bool &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__DeviceRemoveTag(struct soap*, char *_token, char *_deviceID, char *_tag, bool &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__DeviceHasTag(struct soap*, char *_token, char *_deviceID, char *_tag, bool &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__DeviceGetTags(struct soap*, char *_token, char *_deviceID, std::vector<std::string >&result);

SOAP_FMAC5 int SOAP_FMAC6 dss__DeviceLock(struct soap*, char *_token, char *_deviceID, bool &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__DeviceUnlock(struct soap*, char *_token, char *_deviceID, bool &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__DeviceGetIsLocked(struct soap*, char *_token, char *_deviceID, bool &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__DSMeterGetPowerConsumption(struct soap*, char *_token, char *_dsMeterID, unsigned long &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__ApartmentGetDSMeterIDs(struct soap*, char *_token, std::vector<std::string >&ids);

SOAP_FMAC5 int SOAP_FMAC6 dss__DSMeterGetName(struct soap*, char *_token, char *_dsMeterID, std::string &name);

SOAP_FMAC5 int SOAP_FMAC6 dss__DSMeterSetName(struct soap*, char *_token, char *_dsMeterID, char *_name, bool &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__ApartmentAllocateZone(struct soap*, char *_token, int &zoneID);

SOAP_FMAC5 int SOAP_FMAC6 dss__ApartmentDeleteZone(struct soap*, char *_token, int _zoneID, int &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__ZoneSetName(struct soap*, char *_token, int _zoneID, char *_name, bool &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__ZoneGetName(struct soap*, char *_token, int _zoneID, std::string &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__GroupSetName(struct soap*, char *_token, int _zoneID, int _groupID, char *_name, bool &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__GroupGetName(struct soap*, char *_token, int _zoneID, int _groupID, std::string &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__DeviceGetFunctionID(struct soap*, char *_token, char *_deviceID, int &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__EventRaise(struct soap*, char *_token, char *_eventName, char *_context, char *_parameter, char *_location, bool &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__EventWaitFor(struct soap*, char *_token, int _timeout, std::vector<dss__Event >&result);

SOAP_FMAC5 int SOAP_FMAC6 dss__EventSubscribeTo(struct soap*, char *_token, std::string _name, std::string &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__PropertyGetType(struct soap*, char *_token, std::string _propertyName, std::string &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__PropertySetInt(struct soap*, char *_token, std::string _propertyName, int _value, bool _mayCreate, bool &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__PropertySetString(struct soap*, char *_token, std::string _propertyName, char *_value, bool _mayCreate, bool &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__PropertySetBool(struct soap*, char *_token, std::string _propertyName, bool _value, bool _mayCreate, bool &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__PropertyGetInt(struct soap*, char *_token, std::string _propertyName, int &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__PropertyGetString(struct soap*, char *_token, std::string _propertyName, std::string &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__PropertyGetBool(struct soap*, char *_token, std::string _propertyName, bool &result);

SOAP_FMAC5 int SOAP_FMAC6 dss__PropertyGetChildren(struct soap*, char *_token, std::string _propertyName, std::vector<std::string >&result);

SOAP_FMAC5 int SOAP_FMAC6 dss__StructureAddDeviceToZone(struct soap*, char *_token, char *_deviceID, int _zoneID, bool &result);

/******************************************************************************\
 *                                                                            *
 * Skeletons                                                                  *
 *                                                                            *
\******************************************************************************/

SOAP_FMAC5 int SOAP_FMAC6 soap_serve(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_request(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__Authenticate(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__SignOff(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__ApartmentCreateSetFromGroup(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__ApartmentCreateSetFromDeviceIDs(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__ApartmentCreateSetFromDeviceNames(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__ApartmentGetDevices(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__ApartmentGetDeviceIDByName(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__ApartmentGetName(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__ApartmentSetName(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__SetAddDeviceByName(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__SetAddDeviceByID(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__SetRemoveDevice(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__SetCombine(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__SetRemove(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__SetByGroup(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__SetGetContainedDevices(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__ApartmentGetGroupByName(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__ApartmentGetZoneByName(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__ApartmentGetZoneIDs(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__SetTurnOn(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__SetTurnOff(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__SetIncreaseValue(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__SetDecreaseValue(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__SetSetValue(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__SetCallScene(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__SetSaveScene(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__ApartmentTurnOn(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__ApartmentTurnOff(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__ApartmentIncreaseValue(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__ApartmentDecreaseValue(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__ApartmentSetValue(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__ApartmentCallScene(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__ApartmentSaveScene(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__ApartmentRescan(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__CircuitRescan(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__ZoneTurnOn(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__ZoneTurnOff(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__ZoneIncreaseValue(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__ZoneDecreaseValue(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__ZoneSetValue(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__ZoneCallScene(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__ZoneSaveScene(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__DeviceTurnOn(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__DeviceTurnOff(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__DeviceIncreaseValue(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__DeviceDecreaseValue(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__DeviceSetValue(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__DeviceGetValue(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__DeviceCallScene(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__DeviceSaveScene(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__DeviceGetName(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__DeviceSetName(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__DeviceGetZoneID(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__DeviceAddTag(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__DeviceRemoveTag(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__DeviceHasTag(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__DeviceGetTags(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__DeviceLock(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__DeviceUnlock(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__DeviceGetIsLocked(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__DSMeterGetPowerConsumption(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__ApartmentGetDSMeterIDs(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__DSMeterGetName(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__DSMeterSetName(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__ApartmentAllocateZone(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__ApartmentDeleteZone(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__ZoneSetName(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__ZoneGetName(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__GroupSetName(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__GroupGetName(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__DeviceGetFunctionID(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__EventRaise(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__EventWaitFor(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__EventSubscribeTo(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__PropertyGetType(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__PropertySetInt(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__PropertySetString(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__PropertySetBool(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__PropertyGetInt(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__PropertyGetString(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__PropertyGetBool(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__PropertyGetChildren(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dss__StructureAddDeviceToZone(struct soap*);

#endif

/* End of soapStub.h */
